package certification

// CommonCert represents a well-known certification with its issuing provider.
type CommonCert struct {
	Name     string
	Provider string
}

// commonCerts is a curated, alphabetically sorted list of common certifications
// spanning many industries. British English spellings are used where applicable.
var commonCerts = []CommonCert{
	{Name: "AAT Level 2 Certificate in Accounting", Provider: "AAT"},
	{Name: "AAT Level 3 Advanced Diploma in Accounting", Provider: "AAT"},
	{Name: "AAT Level 4 Professional Diploma in Accounting", Provider: "AAT"},
	{Name: "ACA (Associate Chartered Accountant)", Provider: "ICAEW"},
	{Name: "ACCA Applied Knowledge", Provider: "ACCA"},
	{Name: "ACCA Applied Skills", Provider: "ACCA"},
	{Name: "ACCA Strategic Professional", Provider: "ACCA"},
	{Name: "ACLS Provider", Provider: "AHA / Resuscitation Council UK"},
	{Name: "Adobe Certified Professional (InDesign)", Provider: "Adobe"},
	{Name: "Adobe Certified Professional (Premiere Pro)", Provider: "Adobe"},
	{Name: "Advanced Paediatric Life Support (APLS)", Provider: "Resuscitation Council UK"},
	{Name: "ALS (Advanced Life Support) Provider", Provider: "Resuscitation Council UK"},
	{Name: "Alteryx Designer Advanced Certification", Provider: "Alteryx"},
	{Name: "Alteryx Designer Core Certification", Provider: "Alteryx"},
	{Name: "Alteryx Machine Learning Fundamentals", Provider: "Alteryx"},
	{Name: "Anaplan Certified Model Builder", Provider: "Anaplan"},
	{Name: "Anaplan Certified Solution Architect", Provider: "Anaplan"},
	{Name: "APICS CPIM (Certified in Logistics, Transportation and Distribution)", Provider: "ASCM"},
	{Name: "APICS CSCP (Certified Supply Chain Professional)", Provider: "ASCM"},
	{Name: "APM Project Fundamentals Qualification (PFQ)", Provider: "APM"},
	{Name: "APM Project Management Qualification (PMQ)", Provider: "APM"},
	{Name: "APM Project Professional Qualification (PPQ)", Provider: "APM"},
	{Name: "APMG Change Management Foundation", Provider: "APMG International"},
	{Name: "APMG Change Management Practitioner", Provider: "APMG International"},
	{Name: "Appian Certified Associate Developer", Provider: "Appian"},
	{Name: "Appian Certified Senior Developer", Provider: "Appian"},
	{Name: "Apple Certified IT Professional", Provider: "Apple"},
	{Name: "Apple Certified Support Professional (ACSP)", Provider: "Apple"},
	{Name: "ARLA Propertymark Level 3 (Lettings)", Provider: "Propertymark"},
	{Name: "ARLA Propertymark Level 4 (Lettings Management)", Provider: "Propertymark"},
	{Name: "ASQ Certified Quality Auditor (CQA)", Provider: "ASQ"},
	{Name: "ASQ Certified Quality Engineer (CQE)", Provider: "ASQ"},
	{Name: "ASQ Certified Quality Inspector (CQI)", Provider: "ASQ"},
	{Name: "ASQ Certified Reliability Engineer (CRE)", Provider: "ASQ"},
	{Name: "AssocRICS (Associate Member)", Provider: "RICS"},
	{Name: "Atlassian Certified Jira Administrator for Cloud", Provider: "Atlassian"},
	{Name: "Atlassian Certified Jira Project Administrator", Provider: "Atlassian"},
	{Name: "Atlassian Cloud Organisation Admin Certification", Provider: "Atlassian"},
	{Name: "Avid Certified User (Pro Tools)", Provider: "Avid"},
	{Name: "AWS Certified Advanced Networking - Specialty", Provider: "Amazon Web Services"},
	{Name: "AWS Certified AI Practitioner", Provider: "Amazon Web Services"},
	{Name: "AWS Certified Cloud Practitioner", Provider: "Amazon Web Services"},
	{Name: "AWS Certified Data Analytics - Specialty", Provider: "Amazon Web Services"},
	{Name: "AWS Certified Data Engineer - Associate", Provider: "Amazon Web Services"},
	{Name: "AWS Certified Database - Specialty", Provider: "Amazon Web Services"},
	{Name: "AWS Certified Developer - Associate", Provider: "Amazon Web Services"},
	{Name: "AWS Certified DevOps Engineer - Professional", Provider: "Amazon Web Services"},
	{Name: "AWS Certified Machine Learning - Specialty", Provider: "Amazon Web Services"},
	{Name: "AWS Certified Machine Learning Engineer - Associate", Provider: "Amazon Web Services"},
	{Name: "AWS Certified SAP on AWS - Specialty", Provider: "Amazon Web Services"},
	{Name: "AWS Certified Security - Specialty", Provider: "Amazon Web Services"},
	{Name: "AWS Certified Solutions Architect - Associate", Provider: "Amazon Web Services"},
	{Name: "AWS Certified Solutions Architect - Professional", Provider: "Amazon Web Services"},
	{Name: "AWS Certified SysOps Administrator - Associate", Provider: "Amazon Web Services"},
	{Name: "BASIS Certificate in Crop Protection", Provider: "BASIS Registration"},
	{Name: "BCS Certificate in Business Analysis", Provider: "BCS"},
	{Name: "BCS Foundation Certificate in Agile", Provider: "BCS"},
	{Name: "BCS Foundation Certificate in Business Analysis", Provider: "BCS"},
	{Name: "BCS Foundation Certificate in Information Security Management Principles (CISMP)", Provider: "BCS"},
	{Name: "BCS Practitioner Certificate in Data Protection", Provider: "BCS"},
	{Name: "BETA (British Equine Trade Association) Qualification", Provider: "BETA"},
	{Name: "BLS Provider", Provider: "AHA / Resuscitation Council UK"},
	{Name: "Boomi Associate Developer", Provider: "Boomi"},
	{Name: "Boomi Professional Developer", Provider: "Boomi"},
	{Name: "BPEC Gas Safety Certificate", Provider: "BPEC"},
	{Name: "C&G 2396 (Design & Verification of Electrical Installations)", Provider: "City & Guilds"},
	{Name: "CAIA (Chartered Alternative Investment Analyst)", Provider: "CAIA Association"},
	{Name: "CAPM (Certified Associate in Project Management)", Provider: "PMI"},
	{Name: "Care Certificate", Provider: "Skills for Care"},
	{Name: "CBAP (Certified Business Analysis Professional)", Provider: "IIBA"},
	{Name: "CC (Certified in Cybersecurity)", Provider: "ISC2"},
	{Name: "CCAK (Certificate of Cloud Auditing Knowledge)", Provider: "CSA / ISACA"},
	{Name: "CCBA (Certification of Capability in Business Analysis)", Provider: "IIBA"},
	{Name: "CChem (Chartered Chemist)", Provider: "Royal Society of Chemistry"},
	{Name: "CCSK (Certificate of Cloud Security Knowledge)", Provider: "Cloud Security Alliance"},
	{Name: "CCSP (Certified Cloud Security Professional)", Provider: "ISC2"},
	{Name: "CDMP Associate (Certified Data Management Professional)", Provider: "DAMA International"},
	{Name: "CDMP Master", Provider: "DAMA International"},
	{Name: "CDMP Practitioner", Provider: "DAMA International"},
	{Name: "CDPSE (Certified Data Privacy Solutions Engineer)", Provider: "ISACA"},
	{Name: "Celonis Certified Analyst", Provider: "Celonis"},
	{Name: "CEng (Chartered Engineer)", Provider: "Engineering Council"},
	{Name: "Certificate in ESG Investing", Provider: "CFA Institute"},
	{Name: "Certificate in Investment Management (IMC)", Provider: "CFA Institute"},
	{Name: "Certificate in Teaching English to Speakers of Other Languages (CELTA)", Provider: "Cambridge Assessment"},
	{Name: "Certified Blockchain Developer (CBD)", Provider: "Blockchain Council"},
	{Name: "Certified Blockchain Professional (CBP)", Provider: "EC-Council"},
	{Name: "Certified Ethical Hacker (CEH)", Provider: "EC-Council"},
	{Name: "Certified Hacking Forensic Investigator (CHFI)", Provider: "EC-Council"},
	{Name: "Certified Kubernetes Administrator (CKA)", Provider: "CNCF / Linux Foundation"},
	{Name: "Certified Kubernetes Application Developer (CKAD)", Provider: "CNCF / Linux Foundation"},
	{Name: "Certified Kubernetes Security Specialist (CKS)", Provider: "CNCF / Linux Foundation"},
	{Name: "Certified LeSS Practitioner (CLP)", Provider: "LeSS Company"},
	{Name: "Certified Network Defender (CND)", Provider: "EC-Council"},
	{Name: "Certified Penetration Testing Professional (CPENT)", Provider: "EC-Council"},
	{Name: "Certified Product Manager (CPM)", Provider: "AIPMM"},
	{Name: "Certified Scrum Developer (CSD)", Provider: "Scrum Alliance"},
	{Name: "Certified Scrum Master (CSM)", Provider: "Scrum Alliance"},
	{Name: "Certified Scrum Product Owner (CSPO)", Provider: "Scrum Alliance"},
	{Name: "Certified Scrum Professional - Product Owner (CSP-PO)", Provider: "Scrum Alliance"},
	{Name: "Certified Scrum Professional - Scrum Master (CSP-SM)", Provider: "Scrum Alliance"},
	{Name: "CFA Level I", Provider: "CFA Institute"},
	{Name: "CFA Level II", Provider: "CFA Institute"},
	{Name: "CFA Level III", Provider: "CFA Institute"},
	{Name: "CGEIT (Certified in the Governance of Enterprise IT)", Provider: "ISACA"},
	{Name: "Chainalysis Certified Cryptocurrency Investigator (3CI)", Provider: "Chainalysis"},
	{Name: "Check Point Certified Security Administrator (CCSA)", Provider: "Check Point"},
	{Name: "Check Point Certified Security Expert (CCSE)", Provider: "Check Point"},
	{Name: "Cicerone Certified Beer Server", Provider: "Cicerone Certification Programme"},
	{Name: "Cicerone Certified Cicerone", Provider: "Cicerone Certification Programme"},
	{Name: "CILEx Level 3 Professional Diploma in Law and Practice", Provider: "CILEx"},
	{Name: "CILEx Level 6 Professional Higher Diploma in Law and Practice", Provider: "CILEx"},
	{Name: "CILT International Certificate in Logistics & Transport", Provider: "CILT"},
	{Name: "CILT International Diploma in Logistics & Transport", Provider: "CILT"},
	{Name: "CIM Certificate in Professional Marketing", Provider: "Chartered Institute of Marketing"},
	{Name: "CIM Diploma in Professional Marketing", Provider: "Chartered Institute of Marketing"},
	{Name: "CIM Foundation Certificate in Marketing", Provider: "Chartered Institute of Marketing"},
	{Name: "CIMA Certificate in Business Accounting", Provider: "CIMA"},
	{Name: "CIMA Management Level", Provider: "CIMA"},
	{Name: "CIMA Operational Level", Provider: "CIMA"},
	{Name: "CIMA Strategic Level", Provider: "CIMA"},
	{Name: "CIPD Level 3 Foundation Certificate in People Practice", Provider: "CIPD"},
	{Name: "CIPD Level 5 Associate Diploma in Organisational Learning and Development", Provider: "CIPD"},
	{Name: "CIPD Level 5 Associate Diploma in People Management", Provider: "CIPD"},
	{Name: "CIPD Level 7 Advanced Diploma in Strategic Learning and Development", Provider: "CIPD"},
	{Name: "CIPD Level 7 Advanced Diploma in Strategic People Management", Provider: "CIPD"},
	{Name: "CIPM (Certified Information Privacy Manager)", Provider: "IAPP"},
	{Name: "CIPP/E (Certified Information Privacy Professional / Europe)", Provider: "IAPP"},
	{Name: "CIPS Level 3 Advanced Certificate in Procurement & Supply", Provider: "CIPS"},
	{Name: "CIPS Level 4 Diploma in Procurement and Supply", Provider: "CIPS"},
	{Name: "CIPS Level 5 Advanced Diploma in Procurement and Supply", Provider: "CIPS"},
	{Name: "CIPS Level 6 Professional Diploma in Procurement & Supply", Provider: "CIPS"},
	{Name: "CIPT (Certified Information Privacy Technologist)", Provider: "IAPP"},
	{Name: "CISA (Certified Information Systems Auditor)", Provider: "ISACA"},
	{Name: "Cisco CCIE Data Centre", Provider: "Cisco"},
	{Name: "Cisco CCIE Enterprise Infrastructure", Provider: "Cisco"},
	{Name: "Cisco CCIE Security", Provider: "Cisco"},
	{Name: "Cisco CCNA (Cisco Certified Network Associate)", Provider: "Cisco"},
	{Name: "Cisco CCNP Collaboration", Provider: "Cisco"},
	{Name: "Cisco CCNP Data Centre", Provider: "Cisco"},
	{Name: "Cisco CCNP Enterprise", Provider: "Cisco"},
	{Name: "Cisco CCNP Security", Provider: "Cisco"},
	{Name: "Cisco Certified DevNet Associate", Provider: "Cisco"},
	{Name: "Cisco Certified DevNet Expert", Provider: "Cisco"},
	{Name: "Cisco Certified DevNet Professional", Provider: "Cisco"},
	{Name: "Cisco Certified Internetwork Expert (CCIE) Collaboration", Provider: "Cisco"},
	{Name: "CISM (Certified Information Security Manager)", Provider: "ISACA"},
	{Name: "CISSP (Certified Information Systems Security Professional)", Provider: "ISC2"},
	{Name: "CISSP-ISSAP (Information Systems Security Architecture Professional)", Provider: "ISC2"},
	{Name: "CISSP-ISSEP (Information Systems Security Engineering Professional)", Provider: "ISC2"},
	{Name: "CISSP-ISSMP (Information Systems Security Management Professional)", Provider: "ISC2"},
	{Name: "Citrix Certified Associate - Virtualisation (CCA-V)", Provider: "Citrix / Cloud Software Group"},
	{Name: "Citrix Certified Professional - Virtualisation (CCP-V)", Provider: "Citrix / Cloud Software Group"},
	{Name: "City & Guilds 2365 (Electrical Installation)", Provider: "City & Guilds"},
	{Name: "City & Guilds 2382 (18th Edition Wiring Regulations)", Provider: "City & Guilds"},
	{Name: "City & Guilds 2391 (Inspection & Testing)", Provider: "City & Guilds"},
	{Name: "City & Guilds Assessor Awards (TAQA)", Provider: "City & Guilds"},
	{Name: "City & Guilds Bricklaying NVQ Level 2", Provider: "City & Guilds"},
	{Name: "City & Guilds Carpentry & Joinery NVQ Level 2", Provider: "City & Guilds"},
	{Name: "City & Guilds Dental Nursing NVQ", Provider: "City & Guilds"},
	{Name: "City & Guilds Food Preparation & Cooking NVQ", Provider: "City & Guilds"},
	{Name: "City & Guilds Health & Social Care NVQ Level 2", Provider: "City & Guilds"},
	{Name: "City & Guilds Health & Social Care NVQ Level 3", Provider: "City & Guilds"},
	{Name: "City & Guilds Land-Based Studies", Provider: "City & Guilds"},
	{Name: "City & Guilds Photography", Provider: "City & Guilds"},
	{Name: "City & Guilds Plastering NVQ Level 2", Provider: "City & Guilds"},
	{Name: "City & Guilds Plumbing NVQ Level 2", Provider: "City & Guilds"},
	{Name: "Cloudera Certified Associate (CCA) Data Analyst", Provider: "Cloudera"},
	{Name: "Cloudera Data Platform Generalist", Provider: "Cloudera"},
	{Name: "CNCF Certified Argo Project Associate (CAPA)", Provider: "CNCF / Linux Foundation"},
	{Name: "COBIT 2019 Design and Implementation", Provider: "ISACA"},
	{Name: "COBIT 2019 Foundation", Provider: "ISACA"},
	{Name: "CompEx (Competency in Explosive Atmospheres)", Provider: "CompEx/JTL"},
	{Name: "CompTIA A+", Provider: "CompTIA"},
	{Name: "CompTIA CASP+ (Advanced Security Practitioner)", Provider: "CompTIA"},
	{Name: "CompTIA Cloud+", Provider: "CompTIA"},
	{Name: "CompTIA CySA+ (Cybersecurity Analyst)", Provider: "CompTIA"},
	{Name: "CompTIA Data+", Provider: "CompTIA"},
	{Name: "CompTIA DataSys+", Provider: "CompTIA"},
	{Name: "CompTIA ITF+ (IT Fundamentals)", Provider: "CompTIA"},
	{Name: "CompTIA Linux+", Provider: "CompTIA"},
	{Name: "CompTIA Network+", Provider: "CompTIA"},
	{Name: "CompTIA PenTest+", Provider: "CompTIA"},
	{Name: "CompTIA Project+", Provider: "CompTIA"},
	{Name: "CompTIA Security+", Provider: "CompTIA"},
	{Name: "CompTIA SecurityX", Provider: "CompTIA"},
	{Name: "CompTIA Server+", Provider: "CompTIA"},
	{Name: "Confluent Certified Administrator for Apache Kafka", Provider: "Confluent"},
	{Name: "Confluent Certified Developer for Apache Kafka", Provider: "Confluent"},
	{Name: "Coupa Certified Platform User", Provider: "Coupa"},
	{Name: "Court of Master Sommeliers Level 1 (Introductory)", Provider: "Court of Master Sommeliers"},
	{Name: "Court of Master Sommeliers Level 2 (Certified)", Provider: "Court of Master Sommeliers"},
	{Name: "Court of Master Sommeliers Level 3 (Advanced)", Provider: "Court of Master Sommeliers"},
	{Name: "CPA (Certified Public Accountant)", Provider: "AICPA"},
	{Name: "CPCS (Construction Plant Competence Scheme)", Provider: "CITB"},
	{Name: "CRISC (Certified in Risk and Information Systems Control)", Provider: "ISACA"},
	{Name: "CrowdStrike Certified Falcon Administrator (CCFA)", Provider: "CrowdStrike"},
	{Name: "CrowdStrike Certified Falcon Responder (CCFR)", Provider: "CrowdStrike"},
	{Name: "CSci (Chartered Scientist)", Provider: "Science Council"},
	{Name: "CSCS Card (Construction Skills Certification Scheme)", Provider: "CSCS"},
	{Name: "CSSLP (Certified Secure Software Lifecycle Professional)", Provider: "ISC2"},
	{Name: "CyberArk Certified Delivery Engineer (CDE)", Provider: "CyberArk"},
	{Name: "CyberArk Certified Sentry (CPC)", Provider: "CyberArk"},
	{Name: "Dangerous Goods Safety Adviser (DGSA)", Provider: "DfT"},
	{Name: "DASM (Disciplined Agile Scrum Master)", Provider: "PMI"},
	{Name: "Databricks Certified Data Analyst Associate", Provider: "Databricks"},
	{Name: "Databricks Certified Data Engineer Associate", Provider: "Databricks"},
	{Name: "Databricks Certified Data Engineer Professional", Provider: "Databricks"},
	{Name: "Databricks Certified Machine Learning Associate", Provider: "Databricks"},
	{Name: "Databricks Certified Machine Learning Professional", Provider: "Databricks"},
	{Name: "Datadog Fundamentals Certification", Provider: "Datadog"},
	{Name: "Dell Technologies Certified Cloud Architect", Provider: "Dell Technologies"},
	{Name: "Dell Technologies Certified Data Protection Specialist", Provider: "Dell Technologies"},
	{Name: "Dell Technologies Certified Server Specialist", Provider: "Dell Technologies"},
	{Name: "DevOps Foundation", Provider: "DevOps Institute"},
	{Name: "DevOps Leader (DOL)", Provider: "DevOps Institute"},
	{Name: "Diploma in Education and Training (DET) Level 5", Provider: "Various"},
	{Name: "Docker Certified Associate (DCA)", Provider: "Docker"},
	{Name: "Driver CPC (Certificate of Professional Competence)", Provider: "DVSA"},
	{Name: "Dynatrace Associate Certification", Provider: "Dynatrace"},
	{Name: "Dynatrace Professional Certification", Provider: "Dynatrace"},
	{Name: "ECBA (Entry Certificate in Business Analysis)", Provider: "IIBA"},
	{Name: "ECITB Technical Certificate", Provider: "ECITB"},
	{Name: "ECS (Electrotechnical Certification Scheme) Card", Provider: "JIB"},
	{Name: "Elastic Certified Analyst", Provider: "Elastic"},
	{Name: "Elastic Certified Engineer", Provider: "Elastic"},
	{Name: "Elastic Certified Observability Engineer", Provider: "Elastic"},
	{Name: "EngTech (Engineering Technician)", Provider: "Engineering Council"},
	{Name: "EXIN DevOps Master", Provider: "EXIN"},
	{Name: "EXIN Privacy and Data Protection Foundation (PDPF)", Provider: "EXIN"},
	{Name: "EXIN Privacy and Data Protection Practitioner (PDPP)", Provider: "EXIN"},
	{Name: "FACTS (Fertiliser Advisers Certification & Training Scheme)", Provider: "BASIS Registration"},
	{Name: "Fortinet Certified Associate Cybersecurity", Provider: "Fortinet"},
	{Name: "Fortinet NSE 4 Network Security Professional", Provider: "Fortinet"},
	{Name: "Fortinet NSE 7 Enterprise Firewall", Provider: "Fortinet"},
	{Name: "Fortinet NSE 8 Network Security Expert", Provider: "Fortinet"},
	{Name: "FRCS (Fellow of the Royal College of Surgeons)", Provider: "Royal College of Surgeons"},
	{Name: "FRICS (Fellow)", Provider: "RICS"},
	{Name: "FRM Part I (Financial Risk Manager)", Provider: "GARP"},
	{Name: "FRM Part II (Financial Risk Manager)", Provider: "GARP"},
	{Name: "Gas Safe Registration", Provider: "Gas Safe Register"},
	{Name: "GDC (General Dental Council) Registration", Provider: "GDC"},
	{Name: "GIAC Certified Cloud Security Essentials (GCLD)", Provider: "GIAC"},
	{Name: "GIAC Certified Enterprise Defender (GCED)", Provider: "GIAC"},
	{Name: "GIAC Certified Forensic Analyst (GCFA)", Provider: "GIAC"},
	{Name: "GIAC Certified Incident Handler (GCIH)", Provider: "GIAC"},
	{Name: "GIAC Certified Windows Security Administrator (GCWN)", Provider: "GIAC"},
	{Name: "GIAC Cloud Security Automation (GCSA)", Provider: "GIAC"},
	{Name: "GIAC Cloud Threat Detection (GCTD)", Provider: "GIAC"},
	{Name: "GIAC Defensible Security Architecture (GDSA)", Provider: "GIAC"},
	{Name: "GIAC Penetration Tester (GPEN)", Provider: "GIAC"},
	{Name: "GIAC Security Automation (GSAU)", Provider: "GIAC"},
	{Name: "GIAC Security Essentials (GSEC)", Provider: "GIAC"},
	{Name: "GIAC Web Application Penetration Tester (GWAPT)", Provider: "GIAC"},
	{Name: "GitHub Actions Certification", Provider: "GitHub"},
	{Name: "GitHub Administration Certification", Provider: "GitHub"},
	{Name: "GitHub Advanced Security Certification", Provider: "GitHub"},
	{Name: "GitHub Copilot Certification", Provider: "GitHub"},
	{Name: "GitHub Foundations Certification", Provider: "GitHub"},
	{Name: "GitLab Certified Associate", Provider: "GitLab"},
	{Name: "GitLab Certified CI/CD Specialist", Provider: "GitLab"},
	{Name: "GitLab Certified DevOps Professional", Provider: "GitLab"},
	{Name: "GitLab Certified Security Specialist", Provider: "GitLab"},
	{Name: "GOC (General Optical Council) Registration", Provider: "GOC"},
	{Name: "Google Ads Display Certification", Provider: "Google"},
	{Name: "Google Ads Measurement Certification", Provider: "Google"},
	{Name: "Google Ads Search Certification", Provider: "Google"},
	{Name: "Google Ads Shopping Certification", Provider: "Google"},
	{Name: "Google Ads Video Certification", Provider: "Google"},
	{Name: "Google Analytics Individual Qualification (GAIQ)", Provider: "Google"},
	{Name: "Google Analytics Individual Qualification (IQ)", Provider: "Google"},
	{Name: "Google Cloud Associate Cloud Engineer", Provider: "Google Cloud"},
	{Name: "Google Cloud Cloud Digital Leader", Provider: "Google Cloud"},
	{Name: "Google Cloud Professional ChromeOS Administrator", Provider: "Google Cloud"},
	{Name: "Google Cloud Professional Cloud Architect", Provider: "Google Cloud"},
	{Name: "Google Cloud Professional Cloud Database Engineer", Provider: "Google Cloud"},
	{Name: "Google Cloud Professional Cloud Developer", Provider: "Google Cloud"},
	{Name: "Google Cloud Professional Cloud DevOps Engineer", Provider: "Google Cloud"},
	{Name: "Google Cloud Professional Cloud Network Engineer", Provider: "Google Cloud"},
	{Name: "Google Cloud Professional Cloud Security Engineer", Provider: "Google Cloud"},
	{Name: "Google Cloud Professional Cloud Service Mesh Engineer", Provider: "Google Cloud"},
	{Name: "Google Cloud Professional Data Engineer", Provider: "Google Cloud"},
	{Name: "Google Cloud Professional Google Workspace Administrator", Provider: "Google Cloud"},
	{Name: "Google Cloud Professional Machine Learning Engineer", Provider: "Google Cloud"},
	{Name: "Google Digital Garage Fundamentals of Digital Marketing", Provider: "Google"},
	{Name: "Google Project Management Certificate", Provider: "Google"},
	{Name: "GPhC Registration (General Pharmaceutical Council)", Provider: "GPhC"},
	{Name: "GPHR (Global Professional in Human Resources)", Provider: "HRCI"},
	{Name: "GradRSC (Graduate Member)", Provider: "Royal Society of Chemistry"},
	{Name: "Grafana Certified Associate", Provider: "Grafana Labs"},
	{Name: "HashiCorp Certified Consul Associate", Provider: "HashiCorp"},
	{Name: "HashiCorp Certified Terraform Associate", Provider: "HashiCorp"},
	{Name: "HashiCorp Certified Vault Associate", Provider: "HashiCorp"},
	{Name: "HashiCorp Certified Vault Operations Professional", Provider: "HashiCorp"},
	{Name: "HCPC Registration (Health and Care Professions Council)", Provider: "HCPC"},
	{Name: "Hootsuite Platform Certification", Provider: "Hootsuite"},
	{Name: "Hootsuite Social Marketing Certification", Provider: "Hootsuite"},
	{Name: "HubSpot Content Marketing Certification", Provider: "HubSpot"},
	{Name: "HubSpot Email Marketing Certification", Provider: "HubSpot"},
	{Name: "HubSpot Inbound Marketing Certification", Provider: "HubSpot"},
	{Name: "HubSpot Inbound Sales Certification", Provider: "HubSpot"},
	{Name: "HubSpot SEO Certification", Provider: "HubSpot"},
	{Name: "HubSpot Social Media Marketing Certification", Provider: "HubSpot"},
	{Name: "IATA Dangerous Goods Regulations (DGR)", Provider: "IATA"},
	{Name: "IBiol (Institute of Biology) Membership", Provider: "Royal Society of Biology"},
	{Name: "IBM Certified Administrator - Watson IoT Platform", Provider: "IBM"},
	{Name: "IBM Certified Solution Advisor - Watsonx", Provider: "IBM"},
	{Name: "IBM Certified Solution Architect - Cloud Pak for Data", Provider: "IBM"},
	{Name: "IBM Data Engineering Professional Certificate", Provider: "IBM"},
	{Name: "IBM Data Science Professional Certificate", Provider: "IBM"},
	{Name: "ICAEW Certificate in Finance, Accounting and Business (CFAB)", Provider: "ICAEW"},
	{Name: "ICAEW Data Analytics Certificate", Provider: "ICAEW"},
	{Name: "ICAgile Certified Professional (ICP)", Provider: "ICAgile"},
	{Name: "ICAgile Certified Professional in Agile Coaching (ICP-ACC)", Provider: "ICAgile"},
	{Name: "ICAgile Certified Professional in Agile Testing (ICP-TST)", Provider: "ICAgile"},
	{Name: "ICTTech (ICT Technician)", Provider: "Engineering Council"},
	{Name: "IEMA Associate", Provider: "IEMA"},
	{Name: "IEMA Full Membership", Provider: "IEMA"},
	{Name: "IEMA Practitioner", Provider: "IEMA"},
	{Name: "IEng (Incorporated Engineer)", Provider: "Engineering Council"},
	{Name: "IET Wiring Regulations (BS 7671)", Provider: "IET"},
	{Name: "ILS (Immediate Life Support) Provider", Provider: "Resuscitation Council UK"},
	{Name: "IMA Certified Management Accountant (CMA)", Provider: "IMA"},
	{Name: "IMechE Chartered Engineer (via IMechE)", Provider: "IMechE"},
	{Name: "IOSH Managing Safely", Provider: "IOSH"},
	{Name: "IOSH Working Safely", Provider: "IOSH"},
	{Name: "IPAF Operator Licence", Provider: "IPAF"},
	{Name: "IRPM Associate (Residential Property Management)", Provider: "IRPM"},
	{Name: "IRPM Member", Provider: "IRPM"},
	{Name: "ISACA IT Risk Fundamentals", Provider: "ISACA"},
	{Name: "ISO 14001 Lead Auditor (Environmental Management)", Provider: "Various (IRCA Accredited)"},
	{Name: "ISO 22301 Lead Auditor (Business Continuity)", Provider: "Various (IRCA Accredited)"},
	{Name: "ISO 27001 Lead Auditor (Information Security)", Provider: "Various (IRCA Accredited)"},
	{Name: "ISO 27001 Lead Implementer", Provider: "Various (IRCA Accredited)"},
	{Name: "ISO 45001 Lead Auditor (Occupational Health and Safety)", Provider: "Various (IRCA Accredited)"},
	{Name: "ISO 9001 Lead Auditor (Quality Management)", Provider: "Various (IRCA Accredited)"},
	{Name: "ISTQB Agile Tester Extension", Provider: "ISTQB"},
	{Name: "ISTQB Certified Tester Advanced Level - Security Tester", Provider: "ISTQB"},
	{Name: "ISTQB Certified Tester Advanced Level - Technical Test Analyst", Provider: "ISTQB"},
	{Name: "ISTQB Certified Tester Advanced Level - Test Analyst", Provider: "ISTQB"},
	{Name: "ISTQB Certified Tester Advanced Level - Test Manager", Provider: "ISTQB"},
	{Name: "ISTQB Certified Tester Foundation Level (CTFL)", Provider: "ISTQB"},
	{Name: "ITIL 4 Foundation", Provider: "PeopleCert / Axelos"},
	{Name: "ITIL 4 Managing Professional Transition", Provider: "PeopleCert / Axelos"},
	{Name: "ITIL 4 Practice Manager", Provider: "PeopleCert / Axelos"},
	{Name: "ITIL 4 Strategic Leader", Provider: "PeopleCert / Axelos"},
	{Name: "JIB Gold Card (Approved Electrician)", Provider: "JIB"},
	{Name: "Juniper Networks Certified Associate - Junos (JNCIA-Junos)", Provider: "Juniper Networks"},
	{Name: "Juniper Networks Certified Professional - Enterprise Routing and Switching (JNCIP-ENT)", Provider: "Juniper Networks"},
	{Name: "Juniper Networks Certified Specialist - Cloud (JNCIS-Cloud)", Provider: "Juniper Networks"},
	{Name: "Juniper Networks Certified Specialist - Security (JNCIS-SEC)", Provider: "Juniper Networks"},
	{Name: "Kanban Management Professional (KMP)", Provider: "Kanban University"},
	{Name: "Kanban Maturity Model Professional (KMMP)", Provider: "Kanban University"},
	{Name: "Kanban System Design (KSD)", Provider: "Kanban University"},
	{Name: "Kubernetes and Cloud Native Associate (KCNA)", Provider: "CNCF / Linux Foundation"},
	{Name: "Kubernetes and Cloud Native Security Associate (KCSA)", Provider: "CNCF / Linux Foundation"},
	{Name: "LANTRA Awards (Various Agricultural)", Provider: "LANTRA"},
	{Name: "Lean Six Sigma Green Belt", Provider: "Various"},
	{Name: "Lean Six Sigma Yellow Belt", Provider: "Various"},
	{Name: "LEEA (Lifting Equipment Engineers Association) Certificate", Provider: "LEEA"},
	{Name: "Level 2 Award in Food Safety in Catering", Provider: "Highfield/CIEH"},
	{Name: "Level 3 Award in Education and Training (AET)", Provider: "Various"},
	{Name: "Level 3 Award in Food Safety in Catering", Provider: "Highfield/CIEH"},
	{Name: "Level 4 Award in Managing Food Safety", Provider: "Highfield/CIEH"},
	{Name: "Level 5 Certificate in Teaching & Learning", Provider: "Various"},
	{Name: "Level 5 Diploma in Leadership for Health & Social Care", Provider: "Various"},
	{Name: "Licensed Penetration Tester (LPT) Master", Provider: "EC-Council"},
	{Name: "LinkedIn Marketing Labs Certification", Provider: "LinkedIn"},
	{Name: "Linux Foundation Certified System Administrator (LFCS)", Provider: "Linux Foundation"},
	{Name: "LPI Linux Essentials", Provider: "Linux Professional Institute"},
	{Name: "LPIC-1 Linux Administrator", Provider: "Linux Professional Institute"},
	{Name: "LPIC-2 Linux Engineer", Provider: "Linux Professional Institute"},
	{Name: "LPIC-3 Linux Enterprise Professional", Provider: "Linux Professional Institute"},
	{Name: "Makaton Signing", Provider: "The Makaton Charity"},
	{Name: "Meta Certified Community Manager", Provider: "Meta"},
	{Name: "Meta Certified Creative Strategy Professional", Provider: "Meta"},
	{Name: "Meta Certified Digital Marketing Associate", Provider: "Meta"},
	{Name: "Meta Certified Marketing Science Professional", Provider: "Meta"},
	{Name: "MHFA (Mental Health First Aid) Certificate", Provider: "MHFA England"},
	{Name: "Microsoft 365 Certified: Enterprise Administrator Expert (MS-100 and MS-101)", Provider: "Microsoft"},
	{Name: "Microsoft 365 Certified: Messaging Administrator Associate (MS-203)", Provider: "Microsoft"},
	{Name: "Microsoft 365 Certified: Teams Administrator Associate (MS-700)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Azure Administrator Associate (AZ-104)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Azure AI Engineer Associate (AI-102)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Azure AI Fundamentals (AI-900)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Azure Cosmos DB Developer Specialty (DP-420)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Azure Data Engineer Associate (DP-203)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Azure Data Fundamentals (DP-900)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Azure Data Scientist Associate (DP-100)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Azure Database Administrator Associate (DP-300)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Azure Developer Associate (AZ-204)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Azure DevOps Engineer Expert (AZ-400)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Azure for SAP Workloads Specialty (AZ-120)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Azure Fundamentals (AZ-900)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Azure Identity and Access Administrator Associate (SC-300)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Azure IoT Developer Specialty (AZ-220)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Azure Network Engineer Associate (AZ-700)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Azure Security Engineer Associate (AZ-500)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Azure Solutions Architect Expert (AZ-305)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Azure Stack Hub Operator Associate (AZ-600)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Cybersecurity Architect Expert (SC-100)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Dynamics 365 Business Central Functional Consultant Associate (MB-800)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Dynamics 365 Customer Insights (Data) Specialty (MB-260)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Dynamics 365 Fundamentals (CRM) (MB-910)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Dynamics 365 Fundamentals (ERP) (MB-920)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Fabric Analytics Engineer Associate (DP-600)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Identity and Access Administrator Associate (SC-300)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Information Protection and Compliance Administrator Associate (SC-400)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Microsoft 365 Fundamentals (MS-900)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Power Automate RPA Developer Associate (PL-500)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Power BI Data Analyst Associate (PL-300)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Power Platform App Maker Associate (PL-100)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Power Platform Developer Associate (PL-400)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Power Platform Functional Consultant Associate (PL-200)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Power Platform Fundamentals (PL-900)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Power Platform Solution Architect Expert (PL-600)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Security Operations Analyst Associate (SC-200)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Security, Compliance, and Identity Fundamentals (SC-900)", Provider: "Microsoft"},
	{Name: "Microsoft Certified: Windows Server Hybrid Administrator Associate (AZ-800 & AZ-801)", Provider: "Microsoft"},
	{Name: "MikroTik Certified Network Associate (MTCNA)", Provider: "MikroTik"},
	{Name: "MongoDB Certified Atlas Administrator", Provider: "MongoDB"},
	{Name: "MongoDB Certified DBA Associate", Provider: "MongoDB"},
	{Name: "MongoDB Certified Developer Associate", Provider: "MongoDB"},
	{Name: "Moving & Handling Trainer Certificate", Provider: "Various"},
	{Name: "MRCGP (Member of the Royal College of General Practitioners)", Provider: "RCGP"},
	{Name: "MRCP (Member of the Royal College of Physicians)", Provider: "Royal College of Physicians"},
	{Name: "MRCPsych (Member of the Royal College of Psychiatrists)", Provider: "Royal College of Psychiatrists"},
	{Name: "MRICS (Member)", Provider: "RICS"},
	{Name: "MRPharmS (Member of the Royal Pharmaceutical Society)", Provider: "RPS"},
	{Name: "MRSB (Member of the Royal Society of Biology)", Provider: "Royal Society of Biology"},
	{Name: "MuleSoft Certified Developer - Level 1", Provider: "MuleSoft / Salesforce"},
	{Name: "MuleSoft Certified Developer - Level 2", Provider: "MuleSoft / Salesforce"},
	{Name: "MuleSoft Certified Integration Architect - Level 1", Provider: "MuleSoft / Salesforce"},
	{Name: "NAEA Propertymark Level 3 (Sale of Residential Property)", Provider: "Propertymark"},
	{Name: "NAEA Propertymark Level 4 (Residential Estate Agency)", Provider: "Propertymark"},
	{Name: "National Professional Qualification for Headship (NPQH)", Provider: "DfE"},
	{Name: "National Professional Qualification for Leading Behaviour and Culture (NPQLBC)", Provider: "DfE"},
	{Name: "National Professional Qualification for Leading Teacher Development (NPQLTD)", Provider: "DfE"},
	{Name: "National Professional Qualification for Senior Leadership (NPQSL)", Provider: "DfE"},
	{Name: "NCTJ Certificate in Foundation Journalism", Provider: "NCTJ"},
	{Name: "NCTJ Diploma in Journalism", Provider: "NCTJ"},
	{Name: "NEBOSH Certificate in Environmental Management", Provider: "NEBOSH"},
	{Name: "NEBOSH Certificate in Fire Safety", Provider: "NEBOSH"},
	{Name: "NEBOSH International Diploma in Occupational Health and Safety", Provider: "NEBOSH"},
	{Name: "NEBOSH International General Certificate in Occupational Health and Safety", Provider: "NEBOSH"},
	{Name: "NEBOSH National Certificate in Fire Safety", Provider: "NEBOSH"},
	{Name: "NEBOSH National Diploma in Occupational Health and Safety", Provider: "NEBOSH"},
	{Name: "NEBOSH National General Certificate in Occupational Health and Safety", Provider: "NEBOSH"},
	{Name: "NetApp Certified Data Administrator (ONTAP)", Provider: "NetApp"},
	{Name: "NetApp Certified Implementation Engineer (NCIE)", Provider: "NetApp"},
	{Name: "NetSuite Administrator Certification", Provider: "Oracle / NetSuite"},
	{Name: "NetSuite SuiteFoundation Certification", Provider: "Oracle / NetSuite"},
	{Name: "New Relic Certified Observability Practitioner", Provider: "New Relic"},
	{Name: "NICEIC Approved Contractor", Provider: "NICEIC"},
	{Name: "NMC Registration (Nursing and Midwifery Council)", Provider: "NMC"},
	{Name: "NUJ (National Union of Journalists) Membership", Provider: "NUJ"},
	{Name: "Nutanix Certified Associate (NCA)", Provider: "Nutanix"},
	{Name: "Nutanix Certified Professional - Multicloud Infrastructure (NCP-MCI)", Provider: "Nutanix"},
	{Name: "NVIDIA Certified Associate - AI Infrastructure and Operations", Provider: "NVIDIA"},
	{Name: "NVQ Level 6 Construction Site Management", Provider: "Various"},
	{Name: "OCI Architect Associate (Oracle Cloud Infrastructure)", Provider: "Oracle"},
	{Name: "Okta Certified Administrator", Provider: "Okta"},
	{Name: "Okta Certified Developer", Provider: "Okta"},
	{Name: "Okta Certified Professional", Provider: "Okta"},
	{Name: "OpenJS Node.js Application Developer (JSNAD)", Provider: "OpenJS Foundation"},
	{Name: "OpenJS Node.js Services Developer (JSNSD)", Provider: "OpenJS Foundation"},
	{Name: "Oracle Certified Associate Java SE 8 Programmer", Provider: "Oracle"},
	{Name: "Oracle Certified Professional Java SE 17 Developer", Provider: "Oracle"},
	{Name: "Oracle Cloud Infrastructure Architect Associate", Provider: "Oracle"},
	{Name: "Oracle Cloud Infrastructure Architect Professional", Provider: "Oracle"},
	{Name: "Oracle Cloud Infrastructure Foundations Associate", Provider: "Oracle"},
	{Name: "Oracle Database SQL Certified Associate", Provider: "Oracle"},
	{Name: "OSCP (Offensive Security Certified Professional)", Provider: "Offensive Security"},
	{Name: "OSEP (Offensive Security Experienced Penetration Tester)", Provider: "Offensive Security"},
	{Name: "OSWA (Offensive Security Web Assessor)", Provider: "Offensive Security"},
	{Name: "OSWE (Offensive Security Web Expert)", Provider: "Offensive Security"},
	{Name: "OSWP (Offensive Security Wireless Professional)", Provider: "Offensive Security"},
	{Name: "PA1/PA6 (Pesticide Application)", Provider: "City & Guilds / NPTC"},
	{Name: "PagerDuty Certified Incident Responder", Provider: "PagerDuty"},
	{Name: "Palo Alto Networks Certified Cybersecurity Entry-level Technician (PCCET)", Provider: "Palo Alto Networks"},
	{Name: "Palo Alto Networks Certified Detection and Remediation Analyst (PCDRA)", Provider: "Palo Alto Networks"},
	{Name: "Palo Alto Networks Certified Network Security Administrator (PCNSA)", Provider: "Palo Alto Networks"},
	{Name: "Palo Alto Networks Certified Network Security Engineer (PCNSE)", Provider: "Palo Alto Networks"},
	{Name: "PALS Provider (Paediatric Advanced Life Support)", Provider: "AHA / Resuscitation Council UK"},
	{Name: "Part P (Building Regulations for Electrical Work)", Provider: "NICEIC/NAPIT"},
	{Name: "PASMA (Prefabricated Access Suppliers' and Manufacturers' Association)", Provider: "PASMA"},
	{Name: "PECB Certified ISO 22301 Lead Implementer (Business Continuity)", Provider: "PECB"},
	{Name: "PECB Certified ISO 27001 Lead Auditor", Provider: "PECB"},
	{Name: "PECB Certified ISO 27001 Lead Implementer", Provider: "PECB"},
	{Name: "PECB Certified ISO 27701 Lead Implementer (Privacy)", Provider: "PECB"},
	{Name: "PECB Certified ISO 9001 Lead Auditor", Provider: "PECB"},
	{Name: "Personal Licence (Alcohol Licensing)", Provider: "Various Awarding Bodies"},
	{Name: "PGCE (Postgraduate Certificate in Education)", Provider: "Various Universities"},
	{Name: "PgMP (Programme Management Professional)", Provider: "PMI"},
	{Name: "Phlebotomy Certificate", Provider: "NHS / Various"},
	{Name: "PHR (Professional in Human Resources)", Provider: "HRCI"},
	{Name: "PMI-ACP (Agile Certified Practitioner)", Provider: "PMI"},
	{Name: "PMI-PBA (Professional in Business Analysis)", Provider: "PMI"},
	{Name: "PMI-RMP (Risk Management Professional)", Provider: "PMI"},
	{Name: "PMP (Project Management Professional)", Provider: "PMI"},
	{Name: "PRINCE2 Agile Foundation", Provider: "PeopleCert / Axelos"},
	{Name: "PRINCE2 Agile Practitioner", Provider: "PeopleCert / Axelos"},
	{Name: "PRINCE2 Foundation", Provider: "PeopleCert / Axelos"},
	{Name: "PRINCE2 Practitioner", Provider: "PeopleCert / Axelos"},
	{Name: "Product-Led Certification", Provider: "Pendo / Mind the Product"},
	{Name: "Professional Agile Leadership (PAL I)", Provider: "Scrum.org"},
	{Name: "Professional Scrum Master I (PSM I)", Provider: "Scrum.org"},
	{Name: "Professional Scrum Master II (PSM II)", Provider: "Scrum.org"},
	{Name: "Professional Scrum Master III (PSM III)", Provider: "Scrum.org"},
	{Name: "Professional Scrum Product Owner I (PSPO I)", Provider: "Scrum.org"},
	{Name: "Professional Scrum Product Owner II (PSPO II)", Provider: "Scrum.org"},
	{Name: "Professional Scrum with Kanban (PSK I)", Provider: "Scrum.org"},
	{Name: "Prometheus Certified Associate (PCA)", Provider: "CNCF / Linux Foundation"},
	{Name: "Prosci Certified Change Practitioner", Provider: "Prosci"},
	{Name: "Pulumi Certified Cloud Engineer", Provider: "Pulumi"},
	{Name: "Puppet Certified Professional", Provider: "Puppet / Perforce"},
	{Name: "QTS (Qualified Teacher Status)", Provider: "DfE"},
	{Name: "RCSLT Certification (Speech & Language)", Provider: "RCSLT"},
	{Name: "Red Hat Certified Architect (RHCA)", Provider: "Red Hat"},
	{Name: "Red Hat Certified Engineer (RHCE)", Provider: "Red Hat"},
	{Name: "Red Hat Certified Specialist in Ansible Automation", Provider: "Red Hat"},
	{Name: "Red Hat Certified Specialist in OpenShift Administration", Provider: "Red Hat"},
	{Name: "Red Hat Certified System Administrator (RHCSA)", Provider: "Red Hat"},
	{Name: "Red Tractor Assurance", Provider: "Red Tractor"},
	{Name: "RICS APC (Assessment of Professional Competence)", Provider: "RICS"},
	{Name: "RSci (Registered Scientist)", Provider: "Science Council"},
	{Name: "RSciTech (Registered Science Technician)", Provider: "Science Council"},
	{Name: "RSPCA Assured Assessor", Provider: "RSPCA"},
	{Name: "SAFe 6 Agilist (SA)", Provider: "Scaled Agile"},
	{Name: "SAFe 6 DevOps Practitioner (SDP)", Provider: "Scaled Agile"},
	{Name: "SAFe 6 Lean Portfolio Manager (LPM)", Provider: "Scaled Agile"},
	{Name: "SAFe 6 Product Owner / Product Manager (POPM)", Provider: "Scaled Agile"},
	{Name: "SAFe 6 Release Train Engineer (RTE)", Provider: "Scaled Agile"},
	{Name: "SAFe 6 Scrum Master (SSM)", Provider: "Scaled Agile"},
	{Name: "Safeguarding Adults Level 3", Provider: "Various"},
	{Name: "Safeguarding Children Level 3", Provider: "Various"},
	{Name: "Salesforce Certified Administrator", Provider: "Salesforce"},
	{Name: "Salesforce Certified Advanced Administrator", Provider: "Salesforce"},
	{Name: "Salesforce Certified AI Associate", Provider: "Salesforce"},
	{Name: "Salesforce Certified Application Architect", Provider: "Salesforce"},
	{Name: "Salesforce Certified B2C Commerce Developer", Provider: "Salesforce"},
	{Name: "Salesforce Certified Data Cloud Consultant", Provider: "Salesforce"},
	{Name: "Salesforce Certified Experience Cloud Consultant", Provider: "Salesforce"},
	{Name: "Salesforce Certified Integration Architect", Provider: "Salesforce"},
	{Name: "Salesforce Certified Marketing Cloud Consultant", Provider: "Salesforce"},
	{Name: "Salesforce Certified OmniStudio Developer", Provider: "Salesforce"},
	{Name: "Salesforce Certified Platform Developer I", Provider: "Salesforce"},
	{Name: "Salesforce Certified Platform Developer II", Provider: "Salesforce"},
	{Name: "Salesforce Certified Sales Cloud Consultant", Provider: "Salesforce"},
	{Name: "Salesforce Certified Service Cloud Consultant", Provider: "Salesforce"},
	{Name: "Salesforce Certified Tableau CRM and Einstein Discovery Consultant", Provider: "Salesforce"},
	{Name: "SAP Certified Application Associate - SAP S/4HANA", Provider: "SAP"},
	{Name: "SAP Certified Application Associate - SAP S/4HANA Cloud", Provider: "SAP"},
	{Name: "SAP Certified Application Associate - SAP SuccessFactors", Provider: "SAP"},
	{Name: "SAP Certified Development Associate - ABAP", Provider: "SAP"},
	{Name: "SAP Certified Technology Associate - SAP HANA", Provider: "SAP"},
	{Name: "SAS Certified Associate: Programming Fundamentals Using SAS 9.4", Provider: "SAS"},
	{Name: "SAS Certified Specialist: Base Programming Using SAS 9.4", Provider: "SAS"},
	{Name: "Scaffolding NVQ Level 2", Provider: "CISRS"},
	{Name: "SCR (Sustainability and Climate Risk)", Provider: "GARP"},
	{Name: "Scrum Alliance Certified Team Coach (CTC)", Provider: "Scrum Alliance"},
	{Name: "SEN Coordinator (SENCO) Qualification", Provider: "DfE"},
	{Name: "ServiceNow Certified Application Developer (CAD)", Provider: "ServiceNow"},
	{Name: "ServiceNow Certified Application Specialist (CAS)", Provider: "ServiceNow"},
	{Name: "ServiceNow Certified Implementation Specialist (CIS)", Provider: "ServiceNow"},
	{Name: "ServiceNow Certified System Administrator (CSA)", Provider: "ServiceNow"},
	{Name: "ServSafe Food Handler", Provider: "National Restaurant Association"},
	{Name: "ServSafe Manager", Provider: "National Restaurant Association"},
	{Name: "Shopify Partner Certification", Provider: "Shopify"},
	{Name: "SHRM-CP (Certified Professional)", Provider: "SHRM"},
	{Name: "SHRM-SCP (Senior Certified Professional)", Provider: "SHRM"},
	{Name: "Site Management Safety Training Scheme (SMSTS)", Provider: "CITB"},
	{Name: "Site Reliability Engineering (SRE) Foundation", Provider: "DevOps Institute"},
	{Name: "Site Supervisors' Safety Training Scheme (SSSTS)", Provider: "CITB"},
	{Name: "Six Sigma Black Belt", Provider: "ASQ / Various"},
	{Name: "Six Sigma Green Belt", Provider: "ASQ / Various"},
	{Name: "Six Sigma Master Black Belt", Provider: "ASQ / Various"},
	{Name: "Six Sigma Yellow Belt", Provider: "ASQ / Various"},
	{Name: "Snowflake SnowPro Advanced: Administrator", Provider: "Snowflake"},
	{Name: "Snowflake SnowPro Advanced: Architect", Provider: "Snowflake"},
	{Name: "Snowflake SnowPro Advanced: Data Engineer", Provider: "Snowflake"},
	{Name: "Snowflake SnowPro Core Certification", Provider: "Snowflake"},
	{Name: "Snyk Certified Security Champion", Provider: "Snyk"},
	{Name: "Social Work England Registration", Provider: "Social Work England"},
	{Name: "Sophos Certified Administrator", Provider: "Sophos"},
	{Name: "Sophos Certified Engineer", Provider: "Sophos"},
	{Name: "SPHR (Senior Professional in Human Resources)", Provider: "HRCI"},
	{Name: "Splunk Certified Cybersecurity Defense Analyst", Provider: "Splunk"},
	{Name: "Splunk Certified Developer", Provider: "Splunk"},
	{Name: "Splunk Core Certified Advanced Power User", Provider: "Splunk"},
	{Name: "Splunk Core Certified Power User", Provider: "Splunk"},
	{Name: "Splunk Enterprise Certified Admin", Provider: "Splunk"},
	{Name: "SQE1 (Solicitors Qualifying Examination Part 1)", Provider: "SRA"},
	{Name: "SQE2 (Solicitors Qualifying Examination Part 2)", Provider: "SRA"},
	{Name: "SSCP (Systems Security Certified Practitioner)", Provider: "ISC2"},
	{Name: "Stripe Certified Associate Developer", Provider: "Stripe"},
	{Name: "Sumo Logic Certified Professional", Provider: "Sumo Logic"},
	{Name: "Tableau Certified Consultant", Provider: "Tableau / Salesforce"},
	{Name: "Tableau Certified Data Analyst", Provider: "Tableau / Salesforce"},
	{Name: "Tableau Desktop Specialist", Provider: "Tableau / Salesforce"},
	{Name: "Tableau Server Certified Associate", Provider: "Tableau / Salesforce"},
	{Name: "TDS Approved (Tenancy Deposit Scheme)", Provider: "TDS"},
	{Name: "Team Kanban Practitioner (TKP)", Provider: "Kanban University"},
	{Name: "TensorFlow Developer Certificate", Provider: "Google"},
	{Name: "Teradata Vantage Certified Associate", Provider: "Teradata"},
	{Name: "Terraform Associate (003)", Provider: "HashiCorp"},
	{Name: "TIG/MIG/MMA Welding Certification", Provider: "TWI"},
	{Name: "TOGAF 10 Certified", Provider: "The Open Group"},
	{Name: "TOGAF 10 Foundation", Provider: "The Open Group"},
	{Name: "TOGAF Business Architecture Certified", Provider: "The Open Group"},
	{Name: "TPI (The Property Institute) Membership", Provider: "TPI"},
	{Name: "TQUK Level 2 Certificate in Understanding Mental Health", Provider: "TQUK"},
	{Name: "Trinity ATCL Diploma in Music Performance", Provider: "Trinity College London"},
	{Name: "Trinity CertTESOL", Provider: "Trinity College London"},
	{Name: "Twilio Certified Developer", Provider: "Twilio"},
	{Name: "UiPath Certified Advanced RPA Developer (UiARD)", Provider: "UiPath"},
	{Name: "UiPath Certified Professional Automation Developer", Provider: "UiPath"},
	{Name: "UiPath Certified RPA Associate (UiRPA)", Provider: "UiPath"},
	{Name: "Unity Certified Developer", Provider: "Unity Technologies"},
	{Name: "Unity Certified Professional Programmer", Provider: "Unity Technologies"},
	{Name: "Veeam Certified Engineer (VMCE)", Provider: "Veeam"},
	{Name: "Veeam Certified Technical Specialist (VMTSP)", Provider: "Veeam"},
	{Name: "VMware Certified Advanced Professional (VCAP)", Provider: "VMware / Broadcom"},
	{Name: "VMware Certified Professional - Data Centre Virtualisation (VCP-DCV)", Provider: "VMware / Broadcom"},
	{Name: "VMware Certified Professional - Network Virtualisation (VCP-NV)", Provider: "VMware / Broadcom"},
	{Name: "VMware Certified Technical Associate (VCTA)", Provider: "VMware / Broadcom"},
	{Name: "Welding Inspector (CSWIP 3.1)", Provider: "TWI"},
	{Name: "Workday Certified Integration Specialist", Provider: "Workday"},
	{Name: "Workday HCM Certification", Provider: "Workday"},
	{Name: "WSET Level 1 Award in Wines", Provider: "WSET"},
	{Name: "WSET Level 2 Award in Wines & Spirits", Provider: "WSET"},
	{Name: "WSET Level 3 Award in Wines", Provider: "WSET"},
	{Name: "WSET Level 4 Diploma in Wines", Provider: "WSET"},
	{Name: "Zendesk Certified Support Administrator", Provider: "Zendesk"},
	{Name: "Zendesk Certified Support Agent", Provider: "Zendesk"},
	{Name: "Zscaler Certified Cloud Administrator (ZCCA-IA)", Provider: "Zscaler"},
	{Name: "Zscaler Certified Cloud Professional (ZCCP)", Provider: "Zscaler"},
}
