export interface EmojiItem {
  emoji: string;
  name: string;
  keywords: string[];
}

export interface EmojiCategory {
  id: string;
  label: string;
  icon: string;
  emojis: EmojiItem[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: "achievements",
    label: "Achievements",
    icon: "🏆",
    emojis: [
      { emoji: "🏆", name: "Trophy", keywords: ["win", "champion", "first"] },
      { emoji: "🥇", name: "Gold medal", keywords: ["first", "winner", "champion"] },
      { emoji: "🥈", name: "Silver medal", keywords: ["second", "runner-up"] },
      { emoji: "🥉", name: "Bronze medal", keywords: ["third", "place"] },
      { emoji: "🏅", name: "Sports medal", keywords: ["award", "achievement"] },
      { emoji: "🎖️", name: "Military medal", keywords: ["honour", "service", "decoration"] },
      { emoji: "👑", name: "Crown", keywords: ["king", "queen", "royal", "leader"] },
      { emoji: "⭐", name: "Star", keywords: ["favourite", "rating", "gold"] },
      { emoji: "🌟", name: "Glowing star", keywords: ["sparkle", "shine", "brilliant"] },
      { emoji: "💫", name: "Dizzy star", keywords: ["shooting", "wonder", "magic"] },
      { emoji: "✨", name: "Sparkles", keywords: ["magic", "shine", "clean", "new"] },
      { emoji: "🎯", name: "Bullseye", keywords: ["target", "goal", "aim", "direct hit"] },
      { emoji: "🎪", name: "Circus tent", keywords: ["show", "performance", "event"] },
      { emoji: "🎭", name: "Performing arts", keywords: ["theatre", "drama", "masks"] },
      { emoji: "🎬", name: "Clapper board", keywords: ["film", "movie", "action"] },
      { emoji: "🎤", name: "Microphone", keywords: ["sing", "speech", "karaoke", "speak"] },
      { emoji: "🎵", name: "Musical note", keywords: ["music", "song", "melody"] },
      { emoji: "🎶", name: "Musical notes", keywords: ["music", "song", "melody"] },
      { emoji: "🎨", name: "Artist palette", keywords: ["art", "paint", "creative"] },
      { emoji: "🎲", name: "Game die", keywords: ["dice", "luck", "chance", "random"] },
      { emoji: "🏁", name: "Chequered flag", keywords: ["finish", "race", "complete", "done"] },
      { emoji: "🎉", name: "Party popper", keywords: ["celebrate", "congratulations", "hooray"] },
      { emoji: "🎊", name: "Confetti ball", keywords: ["celebrate", "party", "festive"] },
      { emoji: "🎈", name: "Balloon", keywords: ["party", "celebrate", "birthday"] },
      { emoji: "🎁", name: "Wrapped gift", keywords: ["present", "birthday", "reward"] },
      { emoji: "🎗️", name: "Reminder ribbon", keywords: ["awareness", "support", "cause"] },
      { emoji: "📣", name: "Megaphone", keywords: ["announce", "cheer", "loud"] },
      { emoji: "🔔", name: "Bell", keywords: ["notification", "alert", "ring"] },
      { emoji: "💯", name: "Hundred points", keywords: ["perfect", "score", "hundred", "100"] },
      { emoji: "🆕", name: "New", keywords: ["fresh", "start", "begin"] },
      { emoji: "🆙", name: "Up", keywords: ["level", "upgrade", "improve"] },
      { emoji: "✅", name: "Check mark", keywords: ["done", "complete", "correct", "yes"] },
      { emoji: "☑️", name: "Ballot check", keywords: ["tick", "done", "approved"] },
      { emoji: "🏅", name: "Medal", keywords: ["award", "honour", "badge"] },
      { emoji: "🎀", name: "Ribbon", keywords: ["bow", "gift", "decoration"] },
    ],
  },
  {
    id: "people",
    label: "People",
    icon: "😀",
    emojis: [
      { emoji: "😀", name: "Grinning face", keywords: ["happy", "smile", "joy"] },
      { emoji: "😎", name: "Sunglasses face", keywords: ["cool", "confident", "boss"] },
      { emoji: "🤩", name: "Star-struck", keywords: ["excited", "amazed", "wow"] },
      { emoji: "🥳", name: "Party face", keywords: ["celebrate", "birthday", "hooray"] },
      { emoji: "😇", name: "Halo face", keywords: ["angel", "innocent", "blessed"] },
      { emoji: "🤓", name: "Nerd face", keywords: ["smart", "glasses", "geek", "study"] },
      { emoji: "🧠", name: "Brain", keywords: ["smart", "think", "intelligence", "mind"] },
      { emoji: "👀", name: "Eyes", keywords: ["look", "watch", "see", "observe"] },
      { emoji: "👁️", name: "Eye", keywords: ["vision", "sight", "focus"] },
      { emoji: "👍", name: "Thumbs up", keywords: ["approve", "like", "good", "yes"] },
      { emoji: "👏", name: "Clapping hands", keywords: ["applause", "bravo", "congrats"] },
      { emoji: "🙌", name: "Raising hands", keywords: ["celebrate", "hooray", "praise"] },
      { emoji: "🤝", name: "Handshake", keywords: ["deal", "agreement", "partner"] },
      { emoji: "✊", name: "Raised fist", keywords: ["power", "solidarity", "strong"] },
      { emoji: "💪", name: "Flexed biceps", keywords: ["strong", "muscle", "power", "strength"] },
      { emoji: "🖐️", name: "Raised hand", keywords: ["high five", "stop", "wave"] },
      { emoji: "✍️", name: "Writing hand", keywords: ["write", "author", "compose"] },
      { emoji: "🤔", name: "Thinking face", keywords: ["consider", "ponder", "hmm"] },
      { emoji: "🫡", name: "Saluting face", keywords: ["respect", "honour", "salute"] },
      { emoji: "😤", name: "Huffing face", keywords: ["determined", "triumph", "frustrated"] },
      { emoji: "🦸", name: "Superhero", keywords: ["hero", "brave", "power", "save"] },
      { emoji: "🧑‍💻", name: "Technologist", keywords: ["developer", "coder", "programmer"] },
      { emoji: "🧑‍🔬", name: "Scientist", keywords: ["research", "lab", "experiment"] },
      { emoji: "🧑‍🎓", name: "Graduate", keywords: ["student", "education", "degree"] },
      { emoji: "🧑‍🏫", name: "Teacher", keywords: ["educator", "mentor", "professor"] },
      { emoji: "🧑‍🚀", name: "Astronaut", keywords: ["space", "explorer", "nasa"] },
      { emoji: "🧑‍🎨", name: "Artist", keywords: ["creative", "painter", "designer"] },
      { emoji: "🏃", name: "Runner", keywords: ["run", "fast", "sprint", "exercise"] },
      { emoji: "🧗", name: "Climber", keywords: ["climb", "rock", "challenge", "ascend"] },
      { emoji: "🤹", name: "Juggler", keywords: ["juggle", "multitask", "circus"] },
    ],
  },
  {
    id: "sports",
    label: "Sports",
    icon: "⚽",
    emojis: [
      { emoji: "⚽", name: "Football", keywords: ["soccer", "ball", "sport"] },
      { emoji: "🏀", name: "Basketball", keywords: ["ball", "sport", "hoop"] },
      { emoji: "🏈", name: "American football", keywords: ["ball", "sport", "nfl"] },
      { emoji: "⚾", name: "Baseball", keywords: ["ball", "sport"] },
      { emoji: "🎾", name: "Tennis", keywords: ["ball", "sport", "racquet"] },
      { emoji: "🏐", name: "Volleyball", keywords: ["ball", "sport", "beach"] },
      { emoji: "🏉", name: "Rugby", keywords: ["ball", "sport"] },
      { emoji: "🎱", name: "Pool 8 ball", keywords: ["billiards", "snooker"] },
      { emoji: "🏓", name: "Table tennis", keywords: ["ping pong", "paddle"] },
      { emoji: "🏸", name: "Badminton", keywords: ["shuttlecock", "racquet"] },
      { emoji: "🥊", name: "Boxing glove", keywords: ["fight", "punch", "box"] },
      { emoji: "🥋", name: "Martial arts", keywords: ["karate", "judo", "belt"] },
      { emoji: "⛳", name: "Flag in hole", keywords: ["golf", "sport"] },
      { emoji: "🏊", name: "Swimmer", keywords: ["swim", "pool", "water"] },
      { emoji: "🚴", name: "Cyclist", keywords: ["bike", "bicycle", "ride", "cycling"] },
      { emoji: "🏋️", name: "Weight lifter", keywords: ["gym", "strong", "exercise", "lift"] },
      { emoji: "🤸", name: "Cartwheel", keywords: ["gymnastics", "flexible", "acrobat"] },
      { emoji: "🧘", name: "Meditation", keywords: ["yoga", "zen", "calm", "mindful"] },
      { emoji: "🏄", name: "Surfer", keywords: ["surf", "wave", "ocean", "beach"] },
      { emoji: "🎿", name: "Skis", keywords: ["ski", "winter", "snow", "sport"] },
      { emoji: "🏂", name: "Snowboarder", keywords: ["snowboard", "winter", "sport"] },
      { emoji: "🏌️", name: "Golfer", keywords: ["golf", "swing", "sport"] },
      { emoji: "🤺", name: "Fencer", keywords: ["fencing", "sword", "sport"] },
      { emoji: "🏇", name: "Horse racing", keywords: ["jockey", "race", "equestrian"] },
      { emoji: "🎳", name: "Bowling", keywords: ["bowl", "strike", "pins"] },
      { emoji: "🏹", name: "Bow and arrow", keywords: ["archery", "aim", "target"] },
      { emoji: "🥅", name: "Goal net", keywords: ["goal", "score", "football"] },
      { emoji: "🎣", name: "Fishing rod", keywords: ["fish", "catch", "patience"] },
      { emoji: "🥏", name: "Flying disc", keywords: ["frisbee", "throw", "catch"] },
      { emoji: "🪂", name: "Parachute", keywords: ["skydive", "jump", "fall"] },
    ],
  },
  {
    id: "animals",
    label: "Animals",
    icon: "🐾",
    emojis: [
      { emoji: "🦁", name: "Lion", keywords: ["brave", "courage", "king", "strength"] },
      { emoji: "🐯", name: "Tiger", keywords: ["fierce", "powerful", "stripe"] },
      { emoji: "🦅", name: "Eagle", keywords: ["soar", "freedom", "vision", "fly"] },
      { emoji: "🐺", name: "Wolf", keywords: ["pack", "loyal", "wild"] },
      { emoji: "🦊", name: "Fox", keywords: ["clever", "cunning", "smart"] },
      { emoji: "🐻", name: "Bear", keywords: ["strong", "brave", "forest"] },
      { emoji: "🐼", name: "Panda", keywords: ["cute", "bamboo", "peace"] },
      { emoji: "🦄", name: "Unicorn", keywords: ["magic", "rare", "special", "fantasy"] },
      { emoji: "🐉", name: "Dragon", keywords: ["fire", "power", "legend", "mythical"] },
      { emoji: "🦈", name: "Shark", keywords: ["ocean", "predator", "fierce"] },
      { emoji: "🐬", name: "Dolphin", keywords: ["smart", "ocean", "playful"] },
      { emoji: "🦉", name: "Owl", keywords: ["wise", "wisdom", "night", "knowledge"] },
      { emoji: "🦋", name: "Butterfly", keywords: ["transform", "beauty", "change"] },
      { emoji: "🐝", name: "Bee", keywords: ["busy", "honey", "work", "industrious"] },
      { emoji: "🐢", name: "Turtle", keywords: ["slow", "steady", "patience", "shell"] },
      { emoji: "🐙", name: "Octopus", keywords: ["tentacle", "clever", "multitask"] },
      { emoji: "🦎", name: "Lizard", keywords: ["reptile", "adapt", "chameleon"] },
      { emoji: "🐍", name: "Snake", keywords: ["slither", "python", "code"] },
      { emoji: "🦜", name: "Parrot", keywords: ["colourful", "talk", "tropical"] },
      { emoji: "🐧", name: "Penguin", keywords: ["cold", "linux", "tuxedo", "ice"] },
      { emoji: "🦚", name: "Peacock", keywords: ["beautiful", "show", "pride"] },
      { emoji: "🐾", name: "Paw prints", keywords: ["animal", "track", "pet"] },
      { emoji: "🦍", name: "Gorilla", keywords: ["strong", "ape", "power"] },
      { emoji: "🐎", name: "Horse", keywords: ["fast", "race", "gallop"] },
      { emoji: "🐲", name: "Dragon face", keywords: ["fire", "mythical", "legend"] },
      { emoji: "🕊️", name: "Dove", keywords: ["peace", "love", "calm", "bird"] },
      { emoji: "🐋", name: "Whale", keywords: ["ocean", "big", "deep", "sea"] },
      { emoji: "🦩", name: "Flamingo", keywords: ["pink", "tropical", "elegant"] },
      { emoji: "🐊", name: "Crocodile", keywords: ["reptile", "snap", "tough"] },
      { emoji: "🐆", name: "Leopard", keywords: ["fast", "spots", "wild"] },
    ],
  },
  {
    id: "food",
    label: "Food & Drink",
    icon: "🍕",
    emojis: [
      { emoji: "🍕", name: "Pizza", keywords: ["food", "slice", "italian"] },
      { emoji: "🎂", name: "Birthday cake", keywords: ["cake", "celebrate", "party"] },
      { emoji: "🍰", name: "Shortcake", keywords: ["cake", "dessert", "sweet"] },
      { emoji: "🧁", name: "Cupcake", keywords: ["cake", "sweet", "treat"] },
      { emoji: "🍩", name: "Doughnut", keywords: ["donut", "sweet", "treat"] },
      { emoji: "🍪", name: "Biscuit", keywords: ["cookie", "sweet", "treat"] },
      { emoji: "🍫", name: "Chocolate bar", keywords: ["sweet", "cocoa", "treat"] },
      { emoji: "🍿", name: "Popcorn", keywords: ["movie", "snack", "cinema"] },
      { emoji: "☕", name: "Hot beverage", keywords: ["coffee", "tea", "morning", "drink"] },
      { emoji: "🍵", name: "Teacup", keywords: ["tea", "drink", "calm", "british"] },
      { emoji: "🧋", name: "Bubble tea", keywords: ["boba", "drink", "milk tea"] },
      { emoji: "🍺", name: "Beer mug", keywords: ["drink", "pub", "ale", "cheers"] },
      { emoji: "🥂", name: "Clinking glasses", keywords: ["champagne", "toast", "celebrate"] },
      { emoji: "🍾", name: "Bottle with cork", keywords: ["champagne", "celebrate", "pop"] },
      { emoji: "🍷", name: "Wine glass", keywords: ["drink", "red", "elegant"] },
      { emoji: "🧃", name: "Juice box", keywords: ["drink", "juice", "fruit"] },
      { emoji: "🥤", name: "Cup with straw", keywords: ["drink", "soda", "beverage"] },
      { emoji: "🍔", name: "Hamburger", keywords: ["burger", "food", "fast food"] },
      { emoji: "🌮", name: "Taco", keywords: ["food", "mexican"] },
      { emoji: "🍣", name: "Sushi", keywords: ["food", "japanese", "fish"] },
      { emoji: "🥑", name: "Avocado", keywords: ["food", "healthy", "green"] },
      { emoji: "🍎", name: "Red apple", keywords: ["fruit", "food", "healthy", "teacher"] },
      { emoji: "🍋", name: "Lemon", keywords: ["citrus", "sour", "fresh"] },
      { emoji: "🌶️", name: "Hot pepper", keywords: ["spicy", "chilli", "fire"] },
      { emoji: "🍄", name: "Mushroom", keywords: ["fungi", "nature", "power up"] },
    ],
  },
  {
    id: "travel",
    label: "Travel & Places",
    icon: "🌍",
    emojis: [
      { emoji: "🌍", name: "Globe Europe Africa", keywords: ["earth", "world", "planet"] },
      { emoji: "🌎", name: "Globe Americas", keywords: ["earth", "world", "planet"] },
      { emoji: "🌏", name: "Globe Asia Australia", keywords: ["earth", "world", "planet"] },
      { emoji: "🚀", name: "Rocket", keywords: ["launch", "space", "fast", "ship"] },
      { emoji: "🛸", name: "Flying saucer", keywords: ["ufo", "alien", "space"] },
      { emoji: "✈️", name: "Aeroplane", keywords: ["fly", "travel", "flight"] },
      { emoji: "🗺️", name: "World map", keywords: ["map", "travel", "explore"] },
      { emoji: "🧭", name: "Compass", keywords: ["navigate", "direction", "explore"] },
      { emoji: "⛰️", name: "Mountain", keywords: ["peak", "climb", "summit", "challenge"] },
      { emoji: "🏔️", name: "Snow-capped mountain", keywords: ["peak", "summit", "alpine"] },
      { emoji: "🌋", name: "Volcano", keywords: ["erupt", "fire", "power"] },
      { emoji: "🏰", name: "Castle", keywords: ["fortress", "medieval", "kingdom"] },
      { emoji: "🗼", name: "Tokyo Tower", keywords: ["tower", "landmark", "japan"] },
      { emoji: "🗽", name: "Statue of Liberty", keywords: ["freedom", "new york", "usa"] },
      { emoji: "🌅", name: "Sunrise", keywords: ["morning", "dawn", "begin", "new day"] },
      { emoji: "🌄", name: "Sunrise over mountains", keywords: ["morning", "dawn", "scenic"] },
      { emoji: "🌠", name: "Shooting star", keywords: ["wish", "night", "meteor"] },
      { emoji: "🌌", name: "Milky Way", keywords: ["galaxy", "space", "stars", "night"] },
      { emoji: "🏝️", name: "Desert island", keywords: ["tropical", "vacation", "beach"] },
      { emoji: "⛺", name: "Tent", keywords: ["camp", "outdoor", "nature"] },
      { emoji: "🎡", name: "Ferris wheel", keywords: ["fun", "carnival", "amusement"] },
      { emoji: "🚂", name: "Locomotive", keywords: ["train", "steam", "journey"] },
      { emoji: "⛵", name: "Sailboat", keywords: ["sail", "boat", "sea", "wind"] },
      { emoji: "🏗️", name: "Construction crane", keywords: ["build", "construct", "progress"] },
      { emoji: "🌈", name: "Rainbow", keywords: ["colour", "hope", "diversity"] },
    ],
  },
  {
    id: "objects",
    label: "Objects",
    icon: "💡",
    emojis: [
      { emoji: "💡", name: "Light bulb", keywords: ["idea", "bright", "think", "innovation"] },
      { emoji: "📚", name: "Books", keywords: ["read", "study", "library", "learn"] },
      { emoji: "📖", name: "Open book", keywords: ["read", "study", "knowledge"] },
      { emoji: "📝", name: "Memo", keywords: ["note", "write", "document"] },
      { emoji: "💻", name: "Laptop", keywords: ["computer", "code", "work", "tech"] },
      { emoji: "🖥️", name: "Desktop computer", keywords: ["monitor", "screen", "work"] },
      { emoji: "⌨️", name: "Keyboard", keywords: ["type", "code", "input"] },
      { emoji: "🔧", name: "Spanner", keywords: ["wrench", "tool", "fix", "repair"] },
      { emoji: "🔨", name: "Hammer", keywords: ["tool", "build", "construct"] },
      { emoji: "⚙️", name: "Gear", keywords: ["settings", "mechanical", "config"] },
      { emoji: "🔑", name: "Key", keywords: ["lock", "access", "unlock", "secret"] },
      { emoji: "🔒", name: "Locked", keywords: ["secure", "private", "closed"] },
      { emoji: "🔓", name: "Unlocked", keywords: ["open", "access", "free"] },
      { emoji: "💎", name: "Gem stone", keywords: ["diamond", "jewel", "precious", "rare"] },
      {
        emoji: "🔍",
        name: "Magnifying glass left",
        keywords: ["search", "find", "look", "inspect"],
      },
      { emoji: "🔬", name: "Microscope", keywords: ["science", "research", "lab"] },
      { emoji: "🔭", name: "Telescope", keywords: ["space", "stars", "vision", "far"] },
      { emoji: "📡", name: "Satellite antenna", keywords: ["signal", "broadcast", "radar"] },
      { emoji: "🛡️", name: "Shield", keywords: ["protect", "defence", "guard", "security"] },
      { emoji: "⚔️", name: "Crossed swords", keywords: ["battle", "fight", "combat"] },
      { emoji: "🗡️", name: "Dagger", keywords: ["knife", "weapon", "blade"] },
      { emoji: "📊", name: "Bar chart", keywords: ["graph", "stats", "data", "analytics"] },
      { emoji: "📈", name: "Chart increasing", keywords: ["growth", "up", "trend", "profit"] },
      { emoji: "📉", name: "Chart decreasing", keywords: ["down", "loss", "decline"] },
      { emoji: "🧩", name: "Puzzle piece", keywords: ["jigsaw", "fit", "solve", "problem"] },
      { emoji: "🎮", name: "Game controller", keywords: ["gaming", "play", "video game"] },
      { emoji: "🕹️", name: "Joystick", keywords: ["gaming", "arcade", "retro"] },
      { emoji: "📱", name: "Mobile phone", keywords: ["phone", "cell", "smartphone"] },
      { emoji: "💰", name: "Money bag", keywords: ["rich", "cash", "dollar", "wealth"] },
      { emoji: "📦", name: "Package", keywords: ["box", "ship", "delivery", "deploy"] },
      { emoji: "🧲", name: "Magnet", keywords: ["attract", "pull", "magnetic"] },
      { emoji: "🪄", name: "Magic wand", keywords: ["magic", "spell", "wizard"] },
      { emoji: "📋", name: "Clipboard", keywords: ["list", "tasks", "checklist"] },
      { emoji: "🏷️", name: "Label", keywords: ["tag", "price", "category"] },
      { emoji: "⏰", name: "Alarm clock", keywords: ["time", "wake", "deadline"] },
    ],
  },
  {
    id: "symbols",
    label: "Symbols",
    icon: "💜",
    emojis: [
      { emoji: "❤️", name: "Red heart", keywords: ["love", "passion", "favourite"] },
      { emoji: "🧡", name: "Orange heart", keywords: ["love", "warm"] },
      { emoji: "💛", name: "Yellow heart", keywords: ["love", "friendship"] },
      { emoji: "💚", name: "Green heart", keywords: ["love", "nature", "health"] },
      { emoji: "💙", name: "Blue heart", keywords: ["love", "trust", "calm"] },
      { emoji: "💜", name: "Purple heart", keywords: ["love", "luxury"] },
      { emoji: "🖤", name: "Black heart", keywords: ["dark", "goth", "mystery"] },
      { emoji: "🤍", name: "White heart", keywords: ["pure", "clean", "minimal"] },
      { emoji: "💝", name: "Heart with ribbon", keywords: ["love", "gift", "valentine"] },
      { emoji: "🔥", name: "Fire", keywords: ["hot", "flame", "streak", "lit"] },
      { emoji: "⚡", name: "Lightning", keywords: ["bolt", "electric", "power", "fast", "zap"] },
      { emoji: "💥", name: "Collision", keywords: ["boom", "explosion", "impact"] },
      { emoji: "🌀", name: "Cyclone", keywords: ["spin", "dizzy", "spiral", "hurricane"] },
      { emoji: "♻️", name: "Recycling symbol", keywords: ["recycle", "green", "environment"] },
      { emoji: "⚠️", name: "Warning", keywords: ["caution", "alert", "danger"] },
      { emoji: "🚫", name: "Prohibited", keywords: ["forbidden", "banned", "no"] },
      { emoji: "♾️", name: "Infinity", keywords: ["forever", "endless", "loop"] },
      { emoji: "❓", name: "Question mark", keywords: ["ask", "what", "help"] },
      { emoji: "❗", name: "Exclamation mark", keywords: ["alert", "important", "attention"] },
      { emoji: "➡️", name: "Right arrow", keywords: ["next", "forward", "continue"] },
      { emoji: "⬆️", name: "Up arrow", keywords: ["above", "increase", "rise"] },
      { emoji: "🔄", name: "Counterclockwise arrows", keywords: ["refresh", "reload", "sync"] },
      { emoji: "🔀", name: "Shuffle", keywords: ["random", "mix", "shuffle"] },
      { emoji: "▶️", name: "Play button", keywords: ["play", "start", "go", "video"] },
      { emoji: "⏩", name: "Fast forward", keywords: ["skip", "speed", "ahead"] },
      { emoji: "🔴", name: "Red circle", keywords: ["dot", "stop", "record"] },
      { emoji: "🟢", name: "Green circle", keywords: ["dot", "go", "active", "online"] },
      { emoji: "🔵", name: "Blue circle", keywords: ["dot", "info"] },
      { emoji: "🟡", name: "Yellow circle", keywords: ["dot", "warning", "pending"] },
      { emoji: "🟣", name: "Purple circle", keywords: ["dot"] },
    ],
  },
  {
    id: "flags",
    label: "Flags",
    icon: "🚩",
    emojis: [
      { emoji: "🏁", name: "Chequered flag", keywords: ["finish", "race", "done", "complete"] },
      { emoji: "🚩", name: "Triangular flag", keywords: ["flag", "mark", "milestone"] },
      { emoji: "🎌", name: "Crossed flags", keywords: ["flag", "celebrate"] },
      { emoji: "🏴", name: "Black flag", keywords: ["flag", "dark", "pirate"] },
      { emoji: "🏳️", name: "White flag", keywords: ["surrender", "peace", "truce"] },
      { emoji: "🏳️‍🌈", name: "Rainbow flag", keywords: ["pride", "lgbtq", "diversity"] },
      { emoji: "🇬🇧", name: "United Kingdom", keywords: ["uk", "britain", "british", "flag"] },
      { emoji: "🇺🇸", name: "United States", keywords: ["usa", "america", "american", "flag"] },
      { emoji: "🇪🇺", name: "European Union", keywords: ["eu", "europe", "flag"] },
      { emoji: "🇨🇦", name: "Canada", keywords: ["canadian", "maple", "flag"] },
      { emoji: "🇦🇺", name: "Australia", keywords: ["australian", "flag"] },
      { emoji: "🇩🇪", name: "Germany", keywords: ["german", "flag"] },
      { emoji: "🇫🇷", name: "France", keywords: ["french", "flag"] },
      { emoji: "🇯🇵", name: "Japan", keywords: ["japanese", "flag"] },
      { emoji: "🇮🇳", name: "India", keywords: ["indian", "flag"] },
      { emoji: "🇧🇷", name: "Brazil", keywords: ["brazilian", "flag"] },
      { emoji: "🇰🇷", name: "South Korea", keywords: ["korean", "flag"] },
      { emoji: "🇲🇽", name: "Mexico", keywords: ["mexican", "flag"] },
      { emoji: "🇿🇦", name: "South Africa", keywords: ["flag"] },
      { emoji: "🇳🇬", name: "Nigeria", keywords: ["nigerian", "flag"] },
    ],
  },
];

export function searchEmojis(query: string): EmojiItem[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  return EMOJI_CATEGORIES.flatMap((cat) =>
    cat.emojis.filter(
      (e) => e.name.toLowerCase().includes(q) || e.keywords.some((kw) => kw.includes(q)),
    ),
  );
}
