package jobtitle

// commonTitles is a curated, alphabetically sorted list of common job titles
// spanning many industries. British English spellings are used where applicable
// (e.g. "Programme Manager", "Adviser", "Organiser").
var commonTitles = []string{
	"Academic",
	"Accommodation Manager",
	"Account Director",
	"Account Executive",
	"Account Manager",
	"Accountant",
	"Accounts Payable Clerk",
	"Accounts Receivable Clerk",
	"Actuary",
	"Administrative Assistant",
	"Agile Coach",
	"Agricultural Engineer",
	"Agricultural Technician",
	"Agronomist",
	"AI Engineer",
	"AI Research Scientist",
	"Air Cargo Coordinator",
	"Anaesthetist",
	"Analytical Chemist",
	"Analytics Engineer",
	"Analytics Manager",
	"Animal Welfare Officer",
	"Animator",
	"Application Support Analyst",
	"Apprentice",
	"Arborist",
	"Architect",
	"Art Director",
	"Art Therapist",
	"Assembler",
	"Assembly Line Worker",
	"Assistant Chef",
	"Assistant Store Manager",
	"Associate",
	"Associate Director",
	"Associate Professor",
	"Astrophysicist",
	"Audio Engineer",
	"Audiologist",
	"Audit Manager",
	"Auditor",
	"Automation Engineer",
	"Backend Engineer",
	"Baker",
	"Banqueting Manager",
	"Bar Manager",
	"Barista",
	"Barrister",
	"Bartender",
	"Beekeeper",
	"Beverage Manager",
	"Bid Manager",
	"Biochemist",
	"Biodiversity Officer",
	"Bioinformatics Scientist",
	"Biomedical Engineer",
	"Biomedical Scientist",
	"Bookkeeper",
	"Border Force Officer",
	"Branch Manager",
	"Brand Manager",
	"Breakfast Chef",
	"Bricklayer",
	"Broadcast Engineer",
	"Building Control Officer",
	"Building Inspector",
	"Building Standards Officer",
	"Building Surveyor",
	"Bus Driver",
	"Business Analyst",
	"Business Development Director",
	"Business Development Executive",
	"Business Development Manager",
	"Business Intelligence Analyst",
	"Business Intelligence Developer",
	"Butler",
	"Buyer",
	"Cabinet Officer",
	"CAD Technician",
	"Camera Operator",
	"Cardiac Physiologist",
	"Cardiac Technician",
	"Care Assistant",
	"Care Coordinator",
	"Care Home Manager",
	"Care Worker",
	"Carer",
	"Carpenter",
	"Cashier",
	"Casting Director",
	"Category Manager",
	"Cellar Manager",
	"Census Officer",
	"Change Manager",
	"Chaplain",
	"Charity Worker",
	"Chef",
	"Chef de Partie",
	"Chemical Engineer",
	"Chemical Technician",
	"Chemist",
	"Chief Commercial Officer",
	"Chief Data Officer",
	"Chief Executive Officer",
	"Chief Financial Officer",
	"Chief Information Officer",
	"Chief Information Security Officer",
	"Chief Marketing Officer",
	"Chief Medical Officer",
	"Chief Operating Officer",
	"Chief People Officer",
	"Chief Product Officer",
	"Chief Revenue Officer",
	"Chief Strategy Officer",
	"Chief Technology Officer",
	"Child Protection Officer",
	"Children's Home Manager",
	"Chiropodist",
	"Choreographer",
	"Civil Engineer",
	"Civil Servant",
	"Claims Handler",
	"Client Director",
	"Client Manager",
	"Client Partner",
	"Client Relationship Manager",
	"Client Services Manager",
	"Climate Change Officer",
	"Clinical Director",
	"Clinical Lead",
	"Clinical Nurse Specialist",
	"Clinical Psychologist",
	"Clinical Research Associate",
	"Clinical Scientist",
	"Cloud Architect",
	"Cloud Engineer",
	"CNC Machinist",
	"CNC Programmer",
	"Colourist",
	"Commercial Analyst",
	"Commercial Director",
	"Commercial Manager",
	"Commis Chef",
	"Commissioning Editor",
	"Commissioning Engineer",
	"Committee Clerk",
	"Communications Adviser",
	"Communications Director",
	"Communications Manager",
	"Communications Officer",
	"Community Liaison Officer",
	"Community Manager",
	"Community Nurse",
	"Community Safety Officer",
	"Community Support Worker",
	"Community Worker",
	"Company Secretary",
	"Compensation and Benefits Manager",
	"Compliance Analyst",
	"Compliance Manager",
	"Compliance Officer",
	"Comptroller",
	"Conference Manager",
	"Conservation Officer",
	"Consular Officer",
	"Consultant",
	"Consultant Surgeon",
	"Content Designer",
	"Content Editor",
	"Content Manager",
	"Content Strategist",
	"Contracts Manager",
	"Control Systems Engineer",
	"Copywriter",
	"Corporate Communications Manager",
	"Corporate Finance Analyst",
	"Costume Designer",
	"Council Officer",
	"Counsellor",
	"Counter Assistant",
	"Counter Fraud Specialist",
	"Countryside Ranger",
	"Courier",
	"Court Clerk",
	"Crane Operator",
	"Creative Director",
	"Credit Analyst",
	"Credit Controller",
	"Criminologist",
	"CRM Manager",
	"Crop Specialist",
	"Customer Experience Manager",
	"Customer Insight Analyst",
	"Customer Service Adviser",
	"Customer Service Manager",
	"Customer Success Manager",
	"Customs & Excise Officer",
	"Customs Officer",
	"Cyber Security Analyst",
	"Cyber Security Consultant",
	"Cyber Security Engineer",
	"Cyber Security Manager",
	"Cytologist",
	"Dairy Farmer",
	"Data Analyst",
	"Data Architect",
	"Data Engineer",
	"Data Engineering Manager",
	"Data Governance Manager",
	"Data Manager",
	"Data Protection Officer",
	"Data Scientist",
	"Database Administrator",
	"Delivery Driver",
	"Delivery Lead",
	"Delivery Manager",
	"Demand Planner",
	"Demolition Operative",
	"Dental Hygienist",
	"Dental Nurse",
	"Dental Technician",
	"Dentist",
	"Department Manager",
	"Deputy Head Teacher",
	"Dermatologist",
	"Design Director",
	"Design Engineer",
	"Design Lead",
	"Design Manager",
	"Desktop Support Engineer",
	"DevOps Engineer",
	"DevSecOps Engineer",
	"Diagnostic Radiographer",
	"Dialysis Technician",
	"Dietitian",
	"Digital Analyst",
	"Digital Marketing Executive",
	"Digital Marketing Manager",
	"Digital Producer",
	"Digital Product Manager",
	"Digital Project Manager",
	"Digital Transformation Lead",
	"Diplomatic Service Officer",
	"Director",
	"Director of Engineering",
	"Director of Finance",
	"Director of Operations",
	"Director of Sales",
	"Disability Adviser",
	"Disability Assessor",
	"Dispatch Manager",
	"Dispatcher",
	"Distribution Centre Manager",
	"Distribution Manager",
	"District Manager",
	"District Nurse",
	"Dock Worker",
	"Doctor",
	"Documentary Filmmaker",
	"Domiciliary Carer",
	"Drug & Alcohol Worker",
	"Dry Liner",
	"Duty Manager",
	"Duty Manager (Hotel)",
	"E-commerce Manager",
	"Ecologist",
	"Economist",
	"Editor",
	"Editorial Assistant",
	"Education Consultant",
	"Electoral Services Officer",
	"Electrical Engineer",
	"Electrician",
	"Email Marketing Manager",
	"Embedded Software Engineer",
	"Emergency Medical Technician",
	"Endoscopist",
	"Engagement Manager",
	"Engineering Director",
	"Engineering Manager",
	"Enterprise Account Executive",
	"Enterprise Architect",
	"Environmental Compliance Officer",
	"Environmental Consultant",
	"Environmental Engineer",
	"Environmental Health Officer",
	"Environmental Manager",
	"Environmental Scientist",
	"Estimator",
	"Events Coordinator",
	"Events Manager",
	"Executive Assistant",
	"Executive Director",
	"Fabricator",
	"Facilities Coordinator",
	"Facilities Manager",
	"Factory Manager",
	"Factory Supervisor",
	"Family Support Worker",
	"Farm Manager",
	"Farm Worker",
	"Fashion Designer",
	"Fencer",
	"Field Engineer",
	"Field Service Engineer",
	"Film Director",
	"Finance Analyst",
	"Finance Business Partner",
	"Finance Controller",
	"Finance Director",
	"Finance Manager",
	"Finance Officer",
	"Financial Accountant",
	"Financial Adviser",
	"Financial Analyst",
	"Financial Controller",
	"Financial Planner",
	"Fire Safety Engineer",
	"Fire Safety Officer",
	"Firmware Engineer",
	"Fish Farm Manager",
	"Fleet Manager",
	"Floor Manager (TV)",
	"Floor Supervisor",
	"Floorlayer",
	"Food & Beverage Manager",
	"Food Scientist",
	"Food Technologist",
	"Forensic Accountant",
	"Forensic Scientist",
	"Forestry Manager",
	"Forestry Worker",
	"Forklift Driver",
	"Forklift Operator",
	"Foster Care Manager",
	"Foundry Worker",
	"Fraud Analyst",
	"Freedom of Information Officer",
	"Freight Forwarder",
	"Front of House Manager",
	"Frontend Engineer",
	"Full Stack Engineer",
	"Fund Manager",
	"Fundraiser",
	"Fundraising Manager",
	"Gallery Curator",
	"Game Warden",
	"Gas Engineer",
	"General Counsel",
	"General Manager",
	"General Practitioner",
	"Geneticist",
	"Geologist",
	"Geophysicist",
	"GIS Analyst",
	"Glazier",
	"Governance Manager",
	"GP (General Practitioner)",
	"Graphic Designer",
	"Ground Worker",
	"Groundskeeper",
	"Growth Manager",
	"Head Chef",
	"Head Housekeeper",
	"Head of Analytics",
	"Head of Brand",
	"Head of Commercial",
	"Head of Communications",
	"Head of Compliance",
	"Head of Customer Experience",
	"Head of Data",
	"Head of Design",
	"Head of Digital",
	"Head of Engineering",
	"Head of Finance",
	"Head of HR",
	"Head of IT",
	"Head of Legal",
	"Head of Marketing",
	"Head of Operations",
	"Head of People",
	"Head of Procurement",
	"Head of Product",
	"Head of Sales",
	"Head of Security",
	"Head of Strategy",
	"Head of Talent Acquisition",
	"Head Teacher",
	"Health and Safety Adviser",
	"Health and Safety Manager",
	"Health and Safety Officer",
	"Health Economist",
	"Health Inspector",
	"Health Visitor",
	"Healthcare Assistant",
	"Hearing Aid Dispenser",
	"Help Desk Analyst",
	"Herdsperson",
	"HGV Driver",
	"Histologist",
	"Histopathologist",
	"Home Care Assistant",
	"Horticulturist",
	"Hospital Porter",
	"Hospitality Manager",
	"Host",
	"Hotel Manager",
	"Housing Officer",
	"Housing Support Worker",
	"HR Administrator",
	"HR Adviser",
	"HR Analyst",
	"HR Business Partner",
	"HR Coordinator",
	"HR Director",
	"HR Manager",
	"HR Officer",
	"HVAC Technician",
	"Hydraulics Technician",
	"Hydrologist",
	"Illustrator",
	"Immigration Adviser",
	"Immigration Officer",
	"Implementation Consultant",
	"Import/Export Coordinator",
	"Independent Living Adviser",
	"Industrial Designer",
	"Information Analyst",
	"Information Security Manager",
	"Infrastructure Engineer",
	"Inside Sales Representative",
	"Insolvency Practitioner",
	"Inspection Technician",
	"Instrument Technician",
	"Insurance Broker",
	"Insurance Underwriter",
	"Intellectual Property Lawyer",
	"Intelligence Analyst",
	"Intensive Care Nurse",
	"Interaction Designer",
	"Interior Designer",
	"Internal Auditor",
	"Interpreter",
	"Investment Analyst",
	"Investment Manager",
	"IT Consultant",
	"IT Director",
	"IT Manager",
	"IT Project Manager",
	"IT Support Analyst",
	"Joiner",
	"Journalist",
	"Junior Developer",
	"Key Account Manager",
	"Kitchen Manager",
	"Kitchen Porter",
	"Laboratory Manager",
	"Laboratory Technician",
	"Land Agent",
	"Land Surveyor",
	"Landscape Architect",
	"Landscape Gardener",
	"Lead Data Engineer",
	"Lead Data Scientist",
	"Lead Designer",
	"Lead Developer",
	"Lead Software Engineer",
	"Lean Engineer",
	"Learning and Development Adviser",
	"Learning and Development Manager",
	"Learning Designer",
	"Learning Disability Nurse",
	"Lecturer",
	"Legal Adviser",
	"Legal Counsel",
	"Legal Secretary",
	"Librarian",
	"Licensing Officer",
	"Lighting Designer",
	"Lighting Technician",
	"Livestock Manager",
	"Loading Bay Operative",
	"Local Government Officer",
	"Logistics Analyst",
	"Logistics Coordinator",
	"Logistics Manager",
	"Logistics Planner",
	"Machine Learning Engineer",
	"Machine Operator",
	"Machinist",
	"Maintenance Engineer",
	"Maintenance Manager",
	"Maitre d'Hotel",
	"Makeup Artist",
	"Management Accountant",
	"Management Consultant",
	"Manager",
	"Managing Director",
	"Manufacturing Engineer",
	"Marine Biologist",
	"Marine Engineer",
	"Marketing Analyst",
	"Marketing Assistant",
	"Marketing Coordinator",
	"Marketing Director",
	"Marketing Executive",
	"Marketing Manager",
	"Materials Engineer",
	"Materials Scientist",
	"Mathematician",
	"Maxillofacial Surgeon",
	"Mechanical Engineer",
	"Media Buyer",
	"Media Planner",
	"Mediator",
	"Medical Laboratory Assistant",
	"Medical Physicist",
	"Medical Secretary",
	"Medical Writer",
	"Mental Health Nurse",
	"Mental Health Support Worker",
	"Merchandiser",
	"Merchandiser Planner",
	"Metalworker",
	"Meteorologist",
	"Microbiologist",
	"Midwife",
	"Mobile Developer",
	"Motion Designer",
	"Motion Graphics Designer",
	"Music Producer",
	"Music Teacher",
	"Music Therapist",
	"Network Architect",
	"Network Engineer",
	"Network Manager",
	"Neurologist",
	"News Producer",
	"Night Manager",
	"Nurse",
	"Nurse Practitioner",
	"Nursery Nurse",
	"Nursing Associate",
	"Nursing Home Manager",
	"Nutritionist",
	"Occupational Health Adviser",
	"Occupational Therapist",
	"Oceanographer",
	"Office Manager",
	"Operating Department Practitioner",
	"Operations Analyst",
	"Operations Director",
	"Operations Manager",
	"Optician",
	"Optometrist",
	"Organisational Development Consultant",
	"Orthodontist",
	"Orthoptist",
	"Osteopath",
	"Outlet Manager",
	"Paediatrician",
	"Painter & Decorator",
	"Palaeontologist",
	"Palliative Care Nurse",
	"Paralegal",
	"Paramedic",
	"Parcel Sorter",
	"Park Ranger",
	"Particle Physicist",
	"Partner",
	"Partnerships Manager",
	"Pastry Chef",
	"Patent Attorney",
	"Pathologist",
	"Payroll Manager",
	"Payroll Officer",
	"Pensions Adviser",
	"People Partner",
	"Performance Analyst",
	"Performance Marketing Manager",
	"Personal Assistant",
	"Pest Controller",
	"Pharmacist",
	"Pharmacologist",
	"Pharmacy Technician",
	"Phlebotomist",
	"Photographer",
	"Physicist",
	"Physiotherapist",
	"Picture Editor",
	"Planning Manager",
	"Planning Officer",
	"Plant Manager",
	"Plant Operator",
	"Plasterer",
	"Platform Engineer",
	"Plumber",
	"Podiatrist",
	"Policy Adviser",
	"Policy Analyst",
	"Policy Manager",
	"Port Operative",
	"Porter",
	"Portfolio Manager",
	"PPC Specialist",
	"PR Manager",
	"Practice Manager",
	"Practice Nurse",
	"Pre-sales Consultant",
	"Principal Consultant",
	"Principal Designer",
	"Principal Engineer",
	"Principal Software Engineer",
	"Prison Officer",
	"Probation Officer",
	"Process Engineer",
	"Procurement Manager",
	"Procurement Officer",
	"Producer",
	"Product Analyst",
	"Product Designer",
	"Product Director",
	"Product Lead",
	"Product Manager",
	"Product Marketing Manager",
	"Product Owner",
	"Production Assistant",
	"Production Controller",
	"Production Coordinator",
	"Production Designer",
	"Production Line Leader",
	"Production Manager",
	"Production Planner",
	"Production Supervisor",
	"Professor",
	"Programme Coordinator",
	"Programme Director",
	"Programme Manager",
	"Project Coordinator",
	"Project Engineer",
	"Project Manager",
	"Property Manager",
	"Props Master",
	"Prosthetist",
	"Psychiatrist",
	"Psychologist",
	"Psychotherapist",
	"Public Health Consultant",
	"Public Health Officer",
	"Public Relations Manager",
	"Publisher",
	"Purchasing Manager",
	"QA Analyst",
	"QA Engineer",
	"QA Manager",
	"Quality Assurance Manager",
	"Quality Control Inspector",
	"Quality Engineer",
	"Quality Manager",
	"Quantity Surveyor",
	"Radio Presenter",
	"Radiochemist",
	"Radiographer",
	"Radiologist",
	"Real Estate Agent",
	"Receptionist",
	"Records Manager",
	"Recruiter",
	"Recruitment Consultant",
	"Recruitment Manager",
	"Regional Manager",
	"Regional Sales Manager",
	"Regulatory Affairs Manager",
	"Regulatory Affairs Specialist",
	"Regulatory Officer",
	"Relationship Manager",
	"Release Manager",
	"Removals Operative",
	"Renal Nurse",
	"Research Analyst",
	"Research Associate",
	"Research Director",
	"Research Engineer",
	"Research Fellow",
	"Research Scientist",
	"Research Technician",
	"Residential Support Worker",
	"Respite Carer",
	"Restaurant Manager",
	"Retail Assistant",
	"Retail Buyer",
	"Retail Manager",
	"Revenue Manager",
	"Revenue Officer",
	"Rigger (Entertainment)",
	"Risk Analyst",
	"Risk Manager",
	"Robotics Engineer",
	"Roofer",
	"Room Attendant",
	"Route Planner",
	"Runner (TV/Film)",
	"Safeguarding Officer",
	"Safety Engineer",
	"Sales Administrator",
	"Sales Adviser",
	"Sales Analyst",
	"Sales Assistant",
	"Sales Coordinator",
	"Sales Director",
	"Sales Engineer",
	"Sales Executive",
	"Sales Manager",
	"Sales Operations Manager",
	"Sales Representative",
	"Scaffolder",
	"Scene Painter",
	"Science Communicator",
	"Scrub Nurse",
	"Scrum Master",
	"Security Analyst",
	"Security Architect",
	"Security Consultant",
	"Security Engineer",
	"Security Manager",
	"Seismologist",
	"Senior Account Executive",
	"Senior Account Manager",
	"Senior Accountant",
	"Senior Analyst",
	"Senior Architect",
	"Senior Backend Engineer",
	"Senior Business Analyst",
	"Senior Consultant",
	"Senior Data Analyst",
	"Senior Data Engineer",
	"Senior Data Scientist",
	"Senior Designer",
	"Senior Developer",
	"Senior DevOps Engineer",
	"Senior Economist",
	"Senior Engineer",
	"Senior Financial Analyst",
	"Senior Frontend Engineer",
	"Senior Full Stack Engineer",
	"Senior HR Manager",
	"Senior Lecturer",
	"Senior Legal Counsel",
	"Senior Manager",
	"Senior Marketing Manager",
	"Senior Mechanical Engineer",
	"Senior Nurse",
	"Senior Operations Manager",
	"Senior Product Designer",
	"Senior Product Manager",
	"Senior Programme Manager",
	"Senior Project Manager",
	"Senior QA Engineer",
	"Senior Recruiter",
	"Senior Research Scientist",
	"Senior Sales Executive",
	"Senior Sales Manager",
	"Senior Software Engineer",
	"Senior Solutions Architect",
	"Senior Systems Engineer",
	"Senior Technical Architect",
	"Senior UX Designer",
	"Senior UX Researcher",
	"SEO Manager",
	"SEO Specialist",
	"Service Delivery Manager",
	"Service Designer",
	"Service Manager",
	"Set Designer",
	"Sheet Metal Worker",
	"Shepherd",
	"Shipping Clerk",
	"Shop Manager",
	"Site Engineer",
	"Site Manager",
	"Site Reliability Engineer",
	"Social Care Assessor",
	"Social Media Manager",
	"Social Worker",
	"Software Architect",
	"Software Developer",
	"Software Engineer",
	"Soil Scientist",
	"Solicitor",
	"Solutions Architect",
	"Solutions Consultant",
	"Solutions Engineer",
	"Sommelier",
	"Sound Engineer",
	"Sound Technician",
	"Sous Chef",
	"Specialist Nurse",
	"Speech & Language Therapist",
	"Speech and Language Therapist",
	"Staff Engineer",
	"Staff Nurse",
	"Staff Software Engineer",
	"Stage Manager",
	"Statistician",
	"Stock Controller",
	"Stockbroker",
	"Stonemason",
	"Store Detective",
	"Store Manager",
	"Strategy Consultant",
	"Strategy Director",
	"Strategy Manager",
	"Structural Engineer",
	"Studio Manager",
	"Stylist",
	"Sub-Editor",
	"Supply Chain Analyst",
	"Supply Chain Director",
	"Supply Chain Manager",
	"Supply Chain Planner",
	"Support Team Lead",
	"Support Worker",
	"Surgeon",
	"Sustainability Consultant",
	"Sustainability Manager",
	"Systems Administrator",
	"Systems Analyst",
	"Systems Architect",
	"Systems Engineer",
	"Talent Acquisition Manager",
	"Talent Acquisition Partner",
	"Talent Manager",
	"Tax Adviser",
	"Tax Manager",
	"Taxi Driver",
	"Teacher",
	"Teaching Assistant",
	"Team Lead",
	"Technical Account Manager",
	"Technical Analyst",
	"Technical Architect",
	"Technical Author",
	"Technical Consultant",
	"Technical Director",
	"Technical Lead",
	"Technical Manager",
	"Technical Product Manager",
	"Technical Programme Manager",
	"Technical Project Manager",
	"Technical Sales Engineer",
	"Technical Support Engineer",
	"Technical Writer",
	"Technology Director",
	"Telecoms Engineer",
	"Test Analyst",
	"Test Engineer",
	"Test Lead",
	"Test Manager",
	"Test Technician",
	"Theatre Nurse",
	"Tiler",
	"Toolmaker",
	"Town Planner",
	"Toxicologist",
	"Trade Compliance Officer",
	"Trading Standards Officer",
	"Train Driver",
	"Trainer",
	"Training Manager",
	"Translator",
	"Transport Manager",
	"Transport Planner",
	"Treasurer",
	"Treasury Analyst",
	"Tree Surgeon",
	"Trust Manager",
	"UI Designer",
	"UI Developer",
	"Underwriter",
	"User Researcher",
	"UX Designer",
	"UX Lead",
	"UX Researcher",
	"UX Writer",
	"Venue Manager",
	"Veterinary Nurse",
	"Veterinary Surgeon",
	"Vice President",
	"Vice President of Engineering",
	"Vice President of Finance",
	"Vice President of Marketing",
	"Vice President of Operations",
	"Vice President of Product",
	"Vice President of Sales",
	"Videographer",
	"Vision Mixer",
	"Visual Merchandiser",
	"Viticulturist",
	"Voiceover Artist",
	"Volunteer Coordinator",
	"VP of Engineering",
	"Waiter",
	"Ward Manager",
	"Ward Sister",
	"Wardrobe Supervisor",
	"Warehouse Manager",
	"Warehouse Operative",
	"Warehouse Supervisor",
	"Web Designer",
	"Web Developer",
	"Weights & Measures Inspector",
	"Welder",
	"Welfare Officer",
	"Welfare Rights Adviser",
	"Wildlife Biologist",
	"Youth Offending Officer",
	"Youth Worker",
	"Zoologist",
}
