package skill

// CommonSkill represents a well-known skill with its category.
type CommonSkill struct {
	Name     string
	Category string
}

// commonSkills is a curated, alphabetically sorted list of common skills
// spanning many industries. British English spellings are used where applicable.
var commonSkills = []CommonSkill{
	{Name: ".NET", Category: "Frameworks & Libraries"},
	{Name: "3D Modelling (Artistic)", Category: "Creative Arts"},
	{Name: "3D Printing", Category: "Manufacturing & Engineering"},
	{Name: "A/B Testing", Category: "Testing & QA"},
	{Name: "Accessibility Testing", Category: "Testing & QA"},
	{Name: "Account Management", Category: "Retail & Sales"},
	{Name: "Accounts Payable", Category: "Finance & Accounting"},
	{Name: "Accounts Receivable", Category: "Finance & Accounting"},
	{Name: "Acting & Performance", Category: "Creative Arts"},
	{Name: "Active Directory", Category: "Networking"},
	{Name: "Adobe After Effects", Category: "Design"},
	{Name: "Adobe Illustrator", Category: "Design"},
	{Name: "Adobe InDesign", Category: "Design"},
	{Name: "Adobe Photoshop", Category: "Design"},
	{Name: "Adobe XD", Category: "Design"},
	{Name: "Adult Learning Theory", Category: "Education & Training"},
	{Name: "Adult Social Care", Category: "Social Work & Care"},
	{Name: "Agile Methodologies", Category: "Project Management"},
	{Name: "Agricultural Science", Category: "Agriculture & Environment"},
	{Name: "Airflow", Category: "Data & Analytics"},
	{Name: "Anatomy & Physiology", Category: "Healthcare & Medicine"},
	{Name: "Animal Husbandry", Category: "Agriculture & Environment"},
	{Name: "Animation", Category: "Creative Arts"},
	{Name: "Ansible", Category: "DevOps & CI/CD"},
	{Name: "Anti-Money Laundering (AML)", Category: "Finance & Accounting"},
	{Name: "Apache HTTP Server", Category: "Cloud & Infrastructure"},
	{Name: "Apache Kafka", Category: "Data & Analytics"},
	{Name: "Apache Spark", Category: "Data & Analytics"},
	{Name: "API Design", Category: "Web Technologies"},
	{Name: "Applicant Tracking Systems (ATS)", Category: "Human Resources"},
	{Name: "Argo CD", Category: "DevOps & CI/CD"},
	{Name: "Assembly", Category: "Programming Languages"},
	{Name: "Assembly Line Management", Category: "Manufacturing & Engineering"},
	{Name: "Assessment Design", Category: "Education & Training"},
	{Name: "Audio Editing", Category: "Media & Journalism"},
	{Name: "Audit & Assurance", Category: "Finance & Accounting"},
	{Name: "AWS", Category: "Cloud & Infrastructure"},
	{Name: "Azure", Category: "Cloud & Infrastructure"},
	{Name: "B2B Sales", Category: "Retail & Sales"},
	{Name: "Banquet Management", Category: "Hospitality & Catering"},
	{Name: "Bar Operations", Category: "Hospitality & Catering"},
	{Name: "Barista Skills", Category: "Hospitality & Catering"},
	{Name: "Bash", Category: "Programming Languages"},
	{Name: "Behaviour Management", Category: "Education & Training"},
	{Name: "Benefits Administration", Category: "Human Resources"},
	{Name: "BigQuery", Category: "Databases"},
	{Name: "Biodiversity Assessment", Category: "Agriculture & Environment"},
	{Name: "Biostatistics", Category: "Science & Research"},
	{Name: "Blockchain", Category: "Web Technologies"},
	{Name: "Bookkeeping", Category: "Finance & Accounting"},
	{Name: "Bootstrap", Category: "Frameworks & Libraries"},
	{Name: "Brand Strategy", Category: "Marketing & Communications"},
	{Name: "Bricklaying", Category: "Construction & Trades"},
	{Name: "Broadcast Journalism", Category: "Media & Journalism"},
	{Name: "Budget Management (Public Sector)", Category: "Government & Public Sector"},
	{Name: "Budgeting", Category: "Project Management"},
	{Name: "Building Code Compliance", Category: "Construction & Trades"},
	{Name: "Building Information Modelling (BIM)", Category: "Construction & Trades"},
	{Name: "Building Regulations", Category: "Real Estate & Property"},
	{Name: "Buildkite", Category: "DevOps & CI/CD"},
	{Name: "Bun", Category: "Frameworks & Libraries"},
	{Name: "Business Development", Category: "Retail & Sales"},
	{Name: "C", Category: "Programming Languages"},
	{Name: "C#", Category: "Programming Languages"},
	{Name: "C++", Category: "Programming Languages"},
	{Name: "CAD (AutoCAD/Revit)", Category: "Construction & Trades"},
	{Name: "Carbon Footprint Analysis", Category: "Agriculture & Environment"},
	{Name: "Care Planning", Category: "Social Work & Care"},
	{Name: "Carpentry", Category: "Construction & Trades"},
	{Name: "Case Law Analysis", Category: "Legal"},
	{Name: "Case Management", Category: "Social Work & Care"},
	{Name: "Cash Flow Management", Category: "Finance & Accounting"},
	{Name: "Cash Handling", Category: "Retail & Sales"},
	{Name: "Cassandra", Category: "Databases"},
	{Name: "Category Management", Category: "Retail & Sales"},
	{Name: "Catering Operations", Category: "Hospitality & Catering"},
	{Name: "CDN", Category: "Networking"},
	{Name: "Cellar Management", Category: "Hospitality & Catering"},
	{Name: "Character Design", Category: "Creative Arts"},
	{Name: "Chef", Category: "DevOps & CI/CD"},
	{Name: "Chemical Analysis", Category: "Science & Research"},
	{Name: "Child Protection", Category: "Social Work & Care"},
	{Name: "Choreography", Category: "Creative Arts"},
	{Name: "CI/CD Pipelines", Category: "DevOps & CI/CD"},
	{Name: "Cinematography", Category: "Creative Arts"},
	{Name: "CircleCI", Category: "DevOps & CI/CD"},
	{Name: "Classroom Management", Category: "Education & Training"},
	{Name: "Climate Change Adaptation", Category: "Agriculture & Environment"},
	{Name: "Clinical Assessment", Category: "Healthcare & Medicine"},
	{Name: "Clinical Documentation", Category: "Healthcare & Medicine"},
	{Name: "Clinical Research", Category: "Science & Research"},
	{Name: "Clinical Trial Management", Category: "Healthcare & Medicine"},
	{Name: "Clojure", Category: "Programming Languages"},
	{Name: "Cloud Architecture", Category: "Cloud & Infrastructure"},
	{Name: "Cloud Security", Category: "Security"},
	{Name: "CNC Machining", Category: "Manufacturing & Engineering"},
	{Name: "CockroachDB", Category: "Databases"},
	{Name: "Colour Grading", Category: "Creative Arts"},
	{Name: "Colour Theory", Category: "Design"},
	{Name: "Commercial Law", Category: "Legal"},
	{Name: "Commercial Property Management", Category: "Real Estate & Property"},
	{Name: "Communication", Category: "Soft Skills"},
	{Name: "Community Development", Category: "Social Work & Care"},
	{Name: "Community Engagement", Category: "Government & Public Sector"},
	{Name: "Compensation & Benefits", Category: "Human Resources"},
	{Name: "Compliance Management", Category: "Security"},
	{Name: "Composition & Arrangement", Category: "Creative Arts"},
	{Name: "Computer Vision", Category: "AI & Machine Learning"},
	{Name: "Concrete Work", Category: "Construction & Trades"},
	{Name: "Conflict Resolution", Category: "Soft Skills"},
	{Name: "Conflict Resolution (HR)", Category: "Human Resources"},
	{Name: "Confluence", Category: "Project Management"},
	{Name: "Conservation Management", Category: "Agriculture & Environment"},
	{Name: "Consul", Category: "Cloud & Infrastructure"},
	{Name: "Content Management Systems (CMS)", Category: "Media & Journalism"},
	{Name: "Content Marketing", Category: "Marketing & Communications"},
	{Name: "Content Strategy", Category: "Soft Skills"},
	{Name: "Continuous Delivery", Category: "DevOps & CI/CD"},
	{Name: "Continuous Improvement", Category: "Manufacturing & Engineering"},
	{Name: "Continuous Integration", Category: "DevOps & CI/CD"},
	{Name: "Contract Drafting", Category: "Legal"},
	{Name: "Contract Negotiation", Category: "Logistics & Supply Chain"},
	{Name: "Contract Review", Category: "Legal"},
	{Name: "Conveyancing", Category: "Legal"},
	{Name: "Copywriting", Category: "Marketing & Communications"},
	{Name: "Corporate Finance", Category: "Finance & Accounting"},
	{Name: "Corporate Governance", Category: "Legal"},
	{Name: "Counselling", Category: "Social Work & Care"},
	{Name: "Court Procedures", Category: "Legal"},
	{Name: "Credit Analysis", Category: "Finance & Accounting"},
	{Name: "Crisis Intervention", Category: "Social Work & Care"},
	{Name: "Critical Thinking", Category: "Soft Skills"},
	{Name: "CRM Systems", Category: "Retail & Sales"},
	{Name: "Crop Management", Category: "Agriculture & Environment"},
	{Name: "Cross-Border Logistics", Category: "Logistics & Supply Chain"},
	{Name: "Cross-functional Collaboration", Category: "Soft Skills"},
	{Name: "Cryptography", Category: "Security"},
	{Name: "CSS", Category: "Web Technologies"},
	{Name: "Curriculum Design", Category: "Education & Training"},
	{Name: "Customer Retention", Category: "Retail & Sales"},
	{Name: "Customer Service Excellence", Category: "Hospitality & Catering"},
	{Name: "Customs Compliance", Category: "Logistics & Supply Chain"},
	{Name: "Cypress", Category: "Testing & QA"},
	{Name: "Dart", Category: "Programming Languages"},
	{Name: "Data Collection & Sampling", Category: "Science & Research"},
	{Name: "Data Engineering", Category: "Data & Analytics"},
	{Name: "Data Governance", Category: "Data & Analytics"},
	{Name: "Data Modelling", Category: "Data & Analytics"},
	{Name: "Data Visualisation", Category: "Data & Analytics"},
	{Name: "Data Warehousing", Category: "Data & Analytics"},
	{Name: "Datadog", Category: "DevOps & CI/CD"},
	{Name: "dbt", Category: "Data & Analytics"},
	{Name: "Deep Learning", Category: "AI & Machine Learning"},
	{Name: "Demand Planning", Category: "Logistics & Supply Chain"},
	{Name: "Deno", Category: "Frameworks & Libraries"},
	{Name: "Design Systems", Category: "Design"},
	{Name: "Design Thinking", Category: "Design"},
	{Name: "Diagnostic Reasoning", Category: "Healthcare & Medicine"},
	{Name: "Differentiated Instruction", Category: "Education & Training"},
	{Name: "Digital Advertising", Category: "Marketing & Communications"},
	{Name: "Digital Illustration", Category: "Creative Arts"},
	{Name: "Disability Support", Category: "Social Work & Care"},
	{Name: "Distribution Management", Category: "Logistics & Supply Chain"},
	{Name: "Diversity & Inclusion", Category: "Human Resources"},
	{Name: "Django", Category: "Frameworks & Libraries"},
	{Name: "DNS", Category: "Networking"},
	{Name: "Docker", Category: "DevOps & CI/CD"},
	{Name: "Documentary Production", Category: "Media & Journalism"},
	{Name: "Domestic Violence Awareness", Category: "Social Work & Care"},
	{Name: "Drug Administration", Category: "Healthcare & Medicine"},
	{Name: "Due Diligence", Category: "Legal"},
	{Name: "DynamoDB", Category: "Databases"},
	{Name: "E-Commerce Operations", Category: "Retail & Sales"},
	{Name: "E-Learning Development", Category: "Education & Training"},
	{Name: "Echo", Category: "Frameworks & Libraries"},
	{Name: "Editorial Writing", Category: "Media & Journalism"},
	{Name: "Educational Psychology", Category: "Education & Training"},
	{Name: "Elasticsearch", Category: "Databases"},
	{Name: "Electrical Installation", Category: "Construction & Trades"},
	{Name: "Electrical Schematics", Category: "Manufacturing & Engineering"},
	{Name: "Electronic Health Records (EHR)", Category: "Healthcare & Medicine"},
	{Name: "Elixir", Category: "Programming Languages"},
	{Name: "Elm", Category: "Programming Languages"},
	{Name: "Email Marketing", Category: "Marketing & Communications"},
	{Name: "Ember.js", Category: "Frameworks & Libraries"},
	{Name: "Emergency Planning", Category: "Government & Public Sector"},
	{Name: "Emotional Intelligence", Category: "Soft Skills"},
	{Name: "Employee Engagement", Category: "Human Resources"},
	{Name: "Employee Relations", Category: "Human Resources"},
	{Name: "Employment Law", Category: "Legal"},
	{Name: "End-of-Life Care", Category: "Social Work & Care"},
	{Name: "Environmental Impact Assessment", Category: "Agriculture & Environment"},
	{Name: "Environmental Monitoring", Category: "Science & Research"},
	{Name: "Envoy", Category: "Networking"},
	{Name: "Erlang", Category: "Programming Languages"},
	{Name: "Estate Agency", Category: "Real Estate & Property"},
	{Name: "Estimating & Costing", Category: "Construction & Trades"},
	{Name: "ETL", Category: "Data & Analytics"},
	{Name: "Event Coordination", Category: "Hospitality & Catering"},
	{Name: "Event-Driven Architecture", Category: "Cloud & Infrastructure"},
	{Name: "Evidence-Based Policy", Category: "Government & Public Sector"},
	{Name: "Evidence-Based Practice", Category: "Healthcare & Medicine"},
	{Name: "Experimental Design", Category: "Science & Research"},
	{Name: "Express.js", Category: "Frameworks & Libraries"},
	{Name: "Facilities Management", Category: "Real Estate & Property"},
	{Name: "Fact-Checking", Category: "Media & Journalism"},
	{Name: "Failure Mode & Effects Analysis (FMEA)", Category: "Manufacturing & Engineering"},
	{Name: "Family Law", Category: "Legal"},
	{Name: "FastAPI", Category: "Frameworks & Libraries"},
	{Name: "Fastify", Category: "Frameworks & Libraries"},
	{Name: "Field Research", Category: "Science & Research"},
	{Name: "Figma", Category: "Design"},
	{Name: "Film Editing", Category: "Creative Arts"},
	{Name: "Financial Forecasting", Category: "Finance & Accounting"},
	{Name: "Financial Reporting", Category: "Finance & Accounting"},
	{Name: "Financial Statement Analysis", Category: "Finance & Accounting"},
	{Name: "Fine Art", Category: "Creative Arts"},
	{Name: "Firebase", Category: "Cloud & Infrastructure"},
	{Name: "Firewall Configuration", Category: "Networking"},
	{Name: "First Aid & BLS", Category: "Healthcare & Medicine"},
	{Name: "Flask", Category: "Frameworks & Libraries"},
	{Name: "Fleet Management", Category: "Logistics & Supply Chain"},
	{Name: "Flutter", Category: "Mobile Development"},
	{Name: "Food Cost Control", Category: "Hospitality & Catering"},
	{Name: "Food Hygiene & Safety (HACCP)", Category: "Hospitality & Catering"},
	{Name: "Forestry Management", Category: "Agriculture & Environment"},
	{Name: "Fortran", Category: "Programming Languages"},
	{Name: "Freedom of Information", Category: "Government & Public Sector"},
	{Name: "Freight Forwarding", Category: "Logistics & Supply Chain"},
	{Name: "Front of House Management", Category: "Hospitality & Catering"},
	{Name: "Fund Management", Category: "Finance & Accounting"},
	{Name: "GAAP", Category: "Finance & Accounting"},
	{Name: "Gatsby", Category: "Frameworks & Libraries"},
	{Name: "GCP", Category: "Cloud & Infrastructure"},
	{Name: "GDPR Compliance", Category: "Legal"},
	{Name: "Gin", Category: "Frameworks & Libraries"},
	{Name: "Git", Category: "DevOps & CI/CD"},
	{Name: "GitHub Actions", Category: "DevOps & CI/CD"},
	{Name: "GitLab CI", Category: "DevOps & CI/CD"},
	{Name: "Go", Category: "Programming Languages"},
	{Name: "Governance & Accountability", Category: "Government & Public Sector"},
	{Name: "Grafana", Category: "DevOps & CI/CD"},
	{Name: "Grant Administration", Category: "Government & Public Sector"},
	{Name: "Grant Writing", Category: "Science & Research"},
	{Name: "Graphic Design", Category: "Creative Arts"},
	{Name: "GraphQL", Category: "Web Technologies"},
	{Name: "Greenhouse Management", Category: "Agriculture & Environment"},
	{Name: "Groovy", Category: "Programming Languages"},
	{Name: "gRPC", Category: "Web Technologies"},
	{Name: "Guest Relations", Category: "Hospitality & Catering"},
	{Name: "HAProxy", Category: "Networking"},
	{Name: "Haskell", Category: "Programming Languages"},
	{Name: "Health & Safety (CDM)", Category: "Construction & Trades"},
	{Name: "Health & Safety Compliance", Category: "Healthcare & Medicine"},
	{Name: "Helm", Category: "DevOps & CI/CD"},
	{Name: "Hotel Operations", Category: "Hospitality & Catering"},
	{Name: "Housekeeping Management", Category: "Hospitality & Catering"},
	{Name: "HR Analytics", Category: "Human Resources"},
	{Name: "HR Policy Development", Category: "Human Resources"},
	{Name: "HTML", Category: "Web Technologies"},
	{Name: "Hugo", Category: "Frameworks & Libraries"},
	{Name: "HVAC Systems", Category: "Construction & Trades"},
	{Name: "Hypothesis Testing", Category: "Data & Analytics"},
	{Name: "IFRS", Category: "Finance & Accounting"},
	{Name: "Illustration", Category: "Creative Arts"},
	{Name: "Immigration Law", Category: "Legal"},
	{Name: "Import/Export Procedures", Category: "Logistics & Supply Chain"},
	{Name: "Incident Management", Category: "Project Management"},
	{Name: "Incident Response", Category: "Security"},
	{Name: "Industrial Automation", Category: "Manufacturing & Engineering"},
	{Name: "Infection Control", Category: "Healthcare & Medicine"},
	{Name: "Influencer Marketing", Category: "Marketing & Communications"},
	{Name: "Information Architecture", Category: "Design"},
	{Name: "Infrastructure as Code", Category: "Cloud & Infrastructure"},
	{Name: "Instructional Design", Category: "Education & Training"},
	{Name: "Intellectual Property Law", Category: "Legal"},
	{Name: "Interaction Design", Category: "Design"},
	{Name: "Inventory Management", Category: "Retail & Sales"},
	{Name: "Inventory Optimisation", Category: "Logistics & Supply Chain"},
	{Name: "Investigative Journalism", Category: "Media & Journalism"},
	{Name: "Ionic", Category: "Mobile Development"},
	{Name: "iOS Development", Category: "Mobile Development"},
	{Name: "Irrigation Management", Category: "Agriculture & Environment"},
	{Name: "Istio", Category: "Cloud & Infrastructure"},
	{Name: "Java", Category: "Programming Languages"},
	{Name: "JavaScript", Category: "Programming Languages"},
	{Name: "Jenkins", Category: "DevOps & CI/CD"},
	{Name: "Jest", Category: "Testing & QA"},
	{Name: "Jetpack Compose", Category: "Mobile Development"},
	{Name: "Jira", Category: "Project Management"},
	{Name: "Job Evaluation", Category: "Human Resources"},
	{Name: "Joinery", Category: "Construction & Trades"},
	{Name: "jQuery", Category: "Frameworks & Libraries"},
	{Name: "JSON", Category: "Web Technologies"},
	{Name: "Julia", Category: "Programming Languages"},
	{Name: "JUnit", Category: "Testing & QA"},
	{Name: "JWT", Category: "Security"},
	{Name: "Kanban", Category: "Project Management"},
	{Name: "Keras", Category: "AI & Machine Learning"},
	{Name: "Kitchen Management", Category: "Hospitality & Catering"},
	{Name: "Kotlin", Category: "Programming Languages"},
	{Name: "Kubernetes", Category: "Cloud & Infrastructure"},
	{Name: "Labour Law", Category: "Human Resources"},
	{Name: "Land Management", Category: "Agriculture & Environment"},
	{Name: "Land Registry", Category: "Real Estate & Property"},
	{Name: "Laravel", Category: "Frameworks & Libraries"},
	{Name: "Last-Mile Delivery", Category: "Logistics & Supply Chain"},
	{Name: "Leadership", Category: "Soft Skills"},
	{Name: "Lean Manufacturing", Category: "Manufacturing & Engineering"},
	{Name: "Learner Engagement", Category: "Education & Training"},
	{Name: "Learning Management Systems (LMS)", Category: "Education & Training"},
	{Name: "Lease Administration", Category: "Real Estate & Property"},
	{Name: "Legal Research", Category: "Legal"},
	{Name: "Legal Writing", Category: "Legal"},
	{Name: "Lesson Planning", Category: "Education & Training"},
	{Name: "Lettings Management", Category: "Real Estate & Property"},
	{Name: "Linear", Category: "Project Management"},
	{Name: "Linux", Category: "Operating Systems"},
	{Name: "Literature Review", Category: "Science & Research"},
	{Name: "Litigation", Category: "Legal"},
	{Name: "Live Broadcasting", Category: "Media & Journalism"},
	{Name: "Llama", Category: "AI & Machine Learning"},
	{Name: "Load Balancing", Category: "Networking"},
	{Name: "Load Testing", Category: "Testing & QA"},
	{Name: "Looker", Category: "Data & Analytics"},
	{Name: "Loss Prevention", Category: "Retail & Sales"},
	{Name: "Lua", Category: "Programming Languages"},
	{Name: "Machine Learning", Category: "AI & Machine Learning"},
	{Name: "macOS", Category: "Operating Systems"},
	{Name: "Maintenance Planning", Category: "Manufacturing & Engineering"},
	{Name: "Management Accounting", Category: "Finance & Accounting"},
	{Name: "MariaDB", Category: "Databases"},
	{Name: "Market Research", Category: "Marketing & Communications"},
	{Name: "Marketing Analytics", Category: "Marketing & Communications"},
	{Name: "Masonry", Category: "Construction & Trades"},
	{Name: "MATLAB", Category: "Programming Languages"},
	{Name: "Mechanical Design", Category: "Manufacturing & Engineering"},
	{Name: "Media Planning", Category: "Marketing & Communications"},
	{Name: "Mediation & Arbitration", Category: "Legal"},
	{Name: "Medical Coding", Category: "Healthcare & Medicine"},
	{Name: "Medical Terminology", Category: "Healthcare & Medicine"},
	{Name: "Medication Management", Category: "Healthcare & Medicine"},
	{Name: "Memcached", Category: "Databases"},
	{Name: "Mental Health First Aid", Category: "Healthcare & Medicine"},
	{Name: "Mental Health Support", Category: "Social Work & Care"},
	{Name: "Mentoring", Category: "Soft Skills"},
	{Name: "Menu Development", Category: "Hospitality & Catering"},
	{Name: "Merchandising", Category: "Retail & Sales"},
	{Name: "Mergers & Acquisitions", Category: "Legal"},
	{Name: "Microscopy", Category: "Science & Research"},
	{Name: "Microservices", Category: "Cloud & Infrastructure"},
	{Name: "Ministerial Briefing", Category: "Government & Public Sector"},
	{Name: "MLOps", Category: "AI & Machine Learning"},
	{Name: "Mobile UI Design", Category: "Design"},
	{Name: "MongoDB", Category: "Databases"},
	{Name: "Monitoring & Observability", Category: "DevOps & CI/CD"},
	{Name: "Motion Design", Category: "Design"},
	{Name: "Motion Graphics", Category: "Creative Arts"},
	{Name: "MQTT", Category: "Networking"},
	{Name: "Music Production", Category: "Creative Arts"},
	{Name: "Music Theory", Category: "Creative Arts"},
	{Name: "MySQL", Category: "Databases"},
	{Name: "Natural Language Processing", Category: "AI & Machine Learning"},
	{Name: "Needs Assessment", Category: "Social Work & Care"},
	{Name: "Negotiation", Category: "Soft Skills"},
	{Name: "Neo4j", Category: "Databases"},
	{Name: "Nest.js", Category: "Frameworks & Libraries"},
	{Name: "Network Security", Category: "Security"},
	{Name: "News Gathering", Category: "Media & Journalism"},
	{Name: "Next.js", Category: "Frameworks & Libraries"},
	{Name: "Nginx", Category: "Cloud & Infrastructure"},
	{Name: "Node.js", Category: "Frameworks & Libraries"},
	{Name: "NoSQL", Category: "Databases"},
	{Name: "NumPy", Category: "Data & Analytics"},
	{Name: "Nursing Care", Category: "Healthcare & Medicine"},
	{Name: "Nuxt.js", Category: "Frameworks & Libraries"},
	{Name: "OAuth", Category: "Security"},
	{Name: "Objective-C", Category: "Programming Languages"},
	{Name: "Onboarding", Category: "Human Resources"},
	{Name: "OpenAPI / Swagger", Category: "Web Technologies"},
	{Name: "OpenTelemetry", Category: "DevOps & CI/CD"},
	{Name: "Oracle Database", Category: "Databases"},
	{Name: "Order Fulfilment", Category: "Logistics & Supply Chain"},
	{Name: "Organic Farming", Category: "Agriculture & Environment"},
	{Name: "Organisational Development", Category: "Human Resources"},
	{Name: "OWASP", Category: "Security"},
	{Name: "Packer", Category: "DevOps & CI/CD"},
	{Name: "Painting & Decorating", Category: "Construction & Trades"},
	{Name: "Palliative Care", Category: "Social Work & Care"},
	{Name: "Pandas", Category: "Data & Analytics"},
	{Name: "Pastoral Care", Category: "Education & Training"},
	{Name: "Patient Assessment & Triage", Category: "Healthcare & Medicine"},
	{Name: "Patient Safety Protocols", Category: "Healthcare & Medicine"},
	{Name: "Pay-Per-Click (PPC)", Category: "Marketing & Communications"},
	{Name: "Payroll Administration", Category: "Finance & Accounting"},
	{Name: "Pedagogy", Category: "Education & Training"},
	{Name: "Peer Review", Category: "Science & Research"},
	{Name: "Penetration Testing", Category: "Security"},
	{Name: "Performance Management", Category: "Human Resources"},
	{Name: "Performance Optimisation", Category: "Testing & QA"},
	{Name: "Performance Testing", Category: "Testing & QA"},
	{Name: "Perl", Category: "Programming Languages"},
	{Name: "Person-Centred Care", Category: "Social Work & Care"},
	{Name: "Pest Management", Category: "Agriculture & Environment"},
	{Name: "Pharmacy Operations", Category: "Healthcare & Medicine"},
	{Name: "Phlebotomy", Category: "Healthcare & Medicine"},
	{Name: "Photo Editing", Category: "Media & Journalism"},
	{Name: "Photography", Category: "Creative Arts"},
	{Name: "PHP", Category: "Programming Languages"},
	{Name: "Physiotherapy Techniques", Category: "Healthcare & Medicine"},
	{Name: "Plastering", Category: "Construction & Trades"},
	{Name: "Playwright", Category: "Testing & QA"},
	{Name: "PLC Programming", Category: "Manufacturing & Engineering"},
	{Name: "Plumbing", Category: "Construction & Trades"},
	{Name: "Podcast Production", Category: "Media & Journalism"},
	{Name: "Point-of-Sale (POS) Systems", Category: "Retail & Sales"},
	{Name: "Policy Analysis", Category: "Government & Public Sector"},
	{Name: "Policy Development", Category: "Government & Public Sector"},
	{Name: "Portion Control", Category: "Hospitality & Catering"},
	{Name: "PostgreSQL", Category: "Databases"},
	{Name: "Power BI", Category: "Data & Analytics"},
	{Name: "PowerShell", Category: "Programming Languages"},
	{Name: "Precision Agriculture", Category: "Agriculture & Environment"},
	{Name: "Presentation Skills", Category: "Soft Skills"},
	{Name: "Press Release Writing", Category: "Media & Journalism"},
	{Name: "Pricing Strategy", Category: "Retail & Sales"},
	{Name: "PRINCE2", Category: "Project Management"},
	{Name: "Print Design", Category: "Creative Arts"},
	{Name: "Problem Solving", Category: "Soft Skills"},
	{Name: "Process Engineering", Category: "Manufacturing & Engineering"},
	{Name: "Procurement", Category: "Logistics & Supply Chain"},
	{Name: "Product Knowledge", Category: "Retail & Sales"},
	{Name: "Product Management", Category: "Project Management"},
	{Name: "Production Planning", Category: "Manufacturing & Engineering"},
	{Name: "Programme Management", Category: "Government & Public Sector"},
	{Name: "Project Planning (Construction)", Category: "Construction & Trades"},
	{Name: "Prometheus", Category: "DevOps & CI/CD"},
	{Name: "Property Development", Category: "Real Estate & Property"},
	{Name: "Property Law", Category: "Real Estate & Property"},
	{Name: "Property Marketing", Category: "Real Estate & Property"},
	{Name: "Property Valuation", Category: "Real Estate & Property"},
	{Name: "Prototyping", Category: "Design"},
	{Name: "Public Consultation", Category: "Government & Public Sector"},
	{Name: "Public Procurement", Category: "Government & Public Sector"},
	{Name: "Public Relations", Category: "Marketing & Communications"},
	{Name: "Public Sector Finance", Category: "Government & Public Sector"},
	{Name: "Public Speaking", Category: "Soft Skills"},
	{Name: "Pulumi", Category: "Cloud & Infrastructure"},
	{Name: "Puppet", Category: "DevOps & CI/CD"},
	{Name: "pytest", Category: "Testing & QA"},
	{Name: "Python", Category: "Programming Languages"},
	{Name: "PyTorch", Category: "AI & Machine Learning"},
	{Name: "Qualitative Research", Category: "Science & Research"},
	{Name: "Quality Control & Inspection", Category: "Manufacturing & Engineering"},
	{Name: "Quantitative Research", Category: "Science & Research"},
	{Name: "Quantity Surveying", Category: "Construction & Trades"},
	{Name: "R", Category: "Programming Languages"},
	{Name: "RabbitMQ", Category: "Cloud & Infrastructure"},
	{Name: "Radiography", Category: "Healthcare & Medicine"},
	{Name: "React", Category: "Frameworks & Libraries"},
	{Name: "React Native", Category: "Mobile Development"},
	{Name: "Recipe Development", Category: "Hospitality & Catering"},
	{Name: "Recruitment & Selection", Category: "Human Resources"},
	{Name: "Redis", Category: "Databases"},
	{Name: "Redux", Category: "Frameworks & Libraries"},
	{Name: "Regulatory Compliance", Category: "Legal"},
	{Name: "Regulatory Enforcement", Category: "Government & Public Sector"},
	{Name: "Rehabilitation", Category: "Social Work & Care"},
	{Name: "Reinforcement Learning", Category: "AI & Machine Learning"},
	{Name: "Remix", Category: "Frameworks & Libraries"},
	{Name: "Renewable Energy Systems", Category: "Agriculture & Environment"},
	{Name: "Rent Collection", Category: "Real Estate & Property"},
	{Name: "Research Ethics", Category: "Science & Research"},
	{Name: "Research Methodology", Category: "Science & Research"},
	{Name: "Responsive Design", Category: "Web Technologies"},
	{Name: "REST APIs", Category: "Web Technologies"},
	{Name: "Restaurant Management", Category: "Hospitality & Catering"},
	{Name: "Retail Operations", Category: "Retail & Sales"},
	{Name: "Revenue Management", Category: "Hospitality & Catering"},
	{Name: "Risk Assessment", Category: "Finance & Accounting"},
	{Name: "Risk Assessment (Social Care)", Category: "Social Work & Care"},
	{Name: "Risk Management", Category: "Project Management"},
	{Name: "Robot Framework", Category: "Testing & QA"},
	{Name: "Roofing", Category: "Construction & Trades"},
	{Name: "Root Cause Analysis", Category: "Manufacturing & Engineering"},
	{Name: "Route Optimisation", Category: "Logistics & Supply Chain"},
	{Name: "Ruby", Category: "Programming Languages"},
	{Name: "Ruby on Rails", Category: "Frameworks & Libraries"},
	{Name: "Rust", Category: "Programming Languages"},
	{Name: "SaaS Architecture", Category: "Cloud & Infrastructure"},
	{Name: "Safeguarding", Category: "Healthcare & Medicine"},
	{Name: "Safeguarding (Social Care)", Category: "Social Work & Care"},
	{Name: "Safety Management Systems", Category: "Manufacturing & Engineering"},
	{Name: "Sales Forecasting", Category: "Retail & Sales"},
	{Name: "Sales Pipeline Management", Category: "Retail & Sales"},
	{Name: "Scaffolding", Category: "Construction & Trades"},
	{Name: "Scala", Category: "Programming Languages"},
	{Name: "Scientific Writing", Category: "Science & Research"},
	{Name: "scikit-learn", Category: "AI & Machine Learning"},
	{Name: "Screenwriting", Category: "Media & Journalism"},
	{Name: "Scrum", Category: "Project Management"},
	{Name: "Search Engine Marketing (SEM)", Category: "Marketing & Communications"},
	{Name: "Search Engine Optimisation (SEO)", Category: "Marketing & Communications"},
	{Name: "Security Architecture", Category: "Security"},
	{Name: "Security Auditing", Category: "Security"},
	{Name: "Selenium", Category: "Testing & QA"},
	{Name: "SEN/SEND Support", Category: "Education & Training"},
	{Name: "Serverless", Category: "Cloud & Infrastructure"},
	{Name: "Shell Scripting", Category: "Programming Languages"},
	{Name: "Shipping & Receiving", Category: "Logistics & Supply Chain"},
	{Name: "SIEM", Category: "Security"},
	{Name: "Site Acquisition", Category: "Real Estate & Property"},
	{Name: "Site Management", Category: "Construction & Trades"},
	{Name: "Six Sigma", Category: "Manufacturing & Engineering"},
	{Name: "Sketch", Category: "Design"},
	{Name: "Snowflake", Category: "Databases"},
	{Name: "SOAP", Category: "Web Technologies"},
	{Name: "Social Media Management", Category: "Marketing & Communications"},
	{Name: "Social Media Marketing", Category: "Marketing & Communications"},
	{Name: "Socket.IO", Category: "Web Technologies"},
	{Name: "Soil Science", Category: "Agriculture & Environment"},
	{Name: "Solidity", Category: "Programming Languages"},
	{Name: "SolidWorks", Category: "Manufacturing & Engineering"},
	{Name: "SonarQube", Category: "Testing & QA"},
	{Name: "Sound Design", Category: "Creative Arts"},
	{Name: "Spectroscopy", Category: "Science & Research"},
	{Name: "Spring Boot", Category: "Frameworks & Libraries"},
	{Name: "SQL", Category: "Programming Languages"},
	{Name: "SQL Server", Category: "Databases"},
	{Name: "SQLite", Category: "Databases"},
	{Name: "Stage Management", Category: "Creative Arts"},
	{Name: "Stakeholder Communications", Category: "Marketing & Communications"},
	{Name: "Stakeholder Engagement (Public Sector)", Category: "Government & Public Sector"},
	{Name: "Stakeholder Management", Category: "Project Management"},
	{Name: "Statistical Analysis", Category: "Science & Research"},
	{Name: "Stock Control", Category: "Retail & Sales"},
	{Name: "Store Layout & Visual Display", Category: "Retail & Sales"},
	{Name: "Story Development", Category: "Media & Journalism"},
	{Name: "Storyboarding", Category: "Creative Arts"},
	{Name: "Strategic Planning", Category: "Project Management"},
	{Name: "Structural Analysis", Category: "Construction & Trades"},
	{Name: "Student Assessment", Category: "Education & Training"},
	{Name: "Substance Misuse Support", Category: "Social Work & Care"},
	{Name: "Subtitling & Captioning", Category: "Media & Journalism"},
	{Name: "Succession Planning", Category: "Human Resources"},
	{Name: "Supabase", Category: "Cloud & Infrastructure"},
	{Name: "Supply Chain Management", Category: "Manufacturing & Engineering"},
	{Name: "Surveying", Category: "Construction & Trades"},
	{Name: "Sustainability Planning", Category: "Agriculture & Environment"},
	{Name: "Svelte", Category: "Frameworks & Libraries"},
	{Name: "SVN", Category: "DevOps & CI/CD"},
	{Name: "Swift", Category: "Programming Languages"},
	{Name: "SwiftUI", Category: "Mobile Development"},
	{Name: "Tableau", Category: "Data & Analytics"},
	{Name: "Tailwind CSS", Category: "Frameworks & Libraries"},
	{Name: "Talent Management", Category: "Human Resources"},
	{Name: "Tax Compliance", Category: "Finance & Accounting"},
	{Name: "Tax Planning", Category: "Finance & Accounting"},
	{Name: "TCP/IP", Category: "Networking"},
	{Name: "Teaching & Facilitation", Category: "Education & Training"},
	{Name: "Team Building", Category: "Soft Skills"},
	{Name: "Teamwork", Category: "Soft Skills"},
	{Name: "Technical Drawing", Category: "Manufacturing & Engineering"},
	{Name: "Technical Writing", Category: "Soft Skills"},
	{Name: "Tenancy Management", Category: "Real Estate & Property"},
	{Name: "Tenant Relations", Category: "Real Estate & Property"},
	{Name: "TensorFlow", Category: "AI & Machine Learning"},
	{Name: "Terraform", Category: "Cloud & Infrastructure"},
	{Name: "Territory Management", Category: "Retail & Sales"},
	{Name: "Test Automation", Category: "Testing & QA"},
	{Name: "Test-Driven Development", Category: "Testing & QA"},
	{Name: "Testing Strategy", Category: "Testing & QA"},
	{Name: "Threat Modelling", Category: "Security"},
	{Name: "Time Management", Category: "Soft Skills"},
	{Name: "Tooling Design", Category: "Manufacturing & Engineering"},
	{Name: "Traefik", Category: "Networking"},
	{Name: "Training Needs Analysis", Category: "Human Resources"},
	{Name: "Transport Management Systems (TMS)", Category: "Logistics & Supply Chain"},
	{Name: "Trauma-Informed Care", Category: "Social Work & Care"},
	{Name: "Travis CI", Category: "DevOps & CI/CD"},
	{Name: "Treasury Management", Category: "Finance & Accounting"},
	{Name: "Treatment Planning", Category: "Healthcare & Medicine"},
	{Name: "Tutoring & Mentoring", Category: "Education & Training"},
	{Name: "TypeScript", Category: "Programming Languages"},
	{Name: "Typography", Category: "Design"},
	{Name: "Ubuntu", Category: "Operating Systems"},
	{Name: "UI Design", Category: "Design"},
	{Name: "Unit Testing", Category: "Testing & QA"},
	{Name: "Unix", Category: "Operating Systems"},
	{Name: "Unreal Engine", Category: "Frameworks & Libraries"},
	{Name: "Upselling & Cross-selling", Category: "Retail & Sales"},
	{Name: "Usability Testing", Category: "Testing & QA"},
	{Name: "UX Design", Category: "Design"},
	{Name: "UX Research", Category: "Design"},
	{Name: "Vagrant", Category: "DevOps & CI/CD"},
	{Name: "VAT Returns", Category: "Finance & Accounting"},
	{Name: "Vault", Category: "Security"},
	{Name: "Video Editing", Category: "Media & Journalism"},
	{Name: "Video Production", Category: "Media & Journalism"},
	{Name: "Virtual Classroom Facilitation", Category: "Education & Training"},
	{Name: "Vite", Category: "Frameworks & Libraries"},
	{Name: "Voice-Over Production", Category: "Media & Journalism"},
	{Name: "VPN", Category: "Networking"},
	{Name: "Vue.js", Category: "Frameworks & Libraries"},
	{Name: "Vulnerability Assessment", Category: "Security"},
	{Name: "Vulnerable Adult Support", Category: "Social Work & Care"},
	{Name: "Warehouse Management", Category: "Logistics & Supply Chain"},
	{Name: "Warehouse Management Systems (WMS)", Category: "Logistics & Supply Chain"},
	{Name: "Waste Management", Category: "Agriculture & Environment"},
	{Name: "Water Management", Category: "Agriculture & Environment"},
	{Name: "Web Accessibility", Category: "Web Technologies"},
	{Name: "Web Performance", Category: "Web Technologies"},
	{Name: "WebAssembly", Category: "Web Technologies"},
	{Name: "Webpack", Category: "Frameworks & Libraries"},
	{Name: "WebSockets", Category: "Web Technologies"},
	{Name: "Welding", Category: "Construction & Trades"},
	{Name: "Wildlife Management", Category: "Agriculture & Environment"},
	{Name: "Wills & Probate", Category: "Legal"},
	{Name: "Windows Server", Category: "Operating Systems"},
	{Name: "Wine & Beverage Knowledge", Category: "Hospitality & Catering"},
	{Name: "Wireframing", Category: "Design"},
	{Name: "WordPress", Category: "Web Technologies"},
	{Name: "Workforce Planning", Category: "Human Resources"},
	{Name: "Wound Care", Category: "Healthcare & Medicine"},
	{Name: "Xamarin", Category: "Mobile Development"},
	{Name: "XML", Category: "Web Technologies"},
	{Name: "YAML", Category: "Web Technologies"},
	{Name: "Youth Work", Category: "Social Work & Care"},
	{Name: "Zig", Category: "Programming Languages"},
	{Name: "Zsh", Category: "Programming Languages"},
}
