ALTER TABLE users DROP COLUMN IF EXISTS location;
ALTER TABLE users DROP COLUMN IF EXISTS headline;
ALTER TABLE users DROP COLUMN IF EXISTS open_to_work;
ALTER TABLE users DROP COLUMN IF EXISTS linkedin_url;
ALTER TABLE users DROP COLUMN IF EXISTS github_url;
ALTER TABLE users DROP COLUMN IF EXISTS website_url;
